import "dotenv/config";
import { createDb } from "./index";
import * as schema from "./schema";

const db = createDb(process.env.DATABASE_URL!);

const LOREM_BIO =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.";

const LOREM_SYNOPSIS =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet consectetur adipisci velit.";

const CARLO_ACUTIS_BIO_NOTE =
  "Note: Carlo's body was exhumed in 2007 and found to have undergone normal decay (not incorrupt). His remains are displayed in a glass tomb at the Sanctuary of Santa Maria Maggiore in Assisi, covered with a wax layer molded to resemble his living appearance — a common Italian tradition also used for St. John XXIII. The Church has NOT declared his body incorrupt. He wears a tracksuit and sneakers. Popular online claims of incorruptibility are inaccurate.";

async function seed() {
  console.log("Clearing existing data...");
  await db.delete(schema.miracleSources);
  await db.delete(schema.saintLocations);
  await db.delete(schema.saintSources);
  await db.delete(schema.saintRelations);
  await db.delete(schema.miracleSaints);
  await db.delete(schema.miracles);
  await db.delete(schema.saints);

  console.log("Seeding saints...");

  const insertedSaints = await db
    .insert(schema.saints)
    .values([
      {
        slug: "john-paul-ii",
        name: "John Paul II",
        saint_name: "Saint John Paul II",
        birth_name: "Karol Jozef Wojtyla",
        birth_date: "1920-05-18",
        death_date: "2005-04-02",
        feast_day: "October 22",
        nationality: "Polish",
        beatification_date: "2011-05-01",
        beatified_by: "Pope Benedict XVI",
        canonization_date: "2014-04-27",
        canonized_by: "Pope Francis",
        canonization_type: "confessor",
        canonization_stage: "saint",
        patronage: ["World Youth Day", "families", "young Catholics"],
        themes: ["perseverance", "missionaries", "eucharistic", "marian", "conversion"],
        biography_short: LOREM_BIO,
        gender: "male",
        lay_person: false,
        image_url: "https://upload.wikimedia.org/wikipedia/commons/3/34/JPII_29_09_2004_2.JPG",
        wikipedia_url: "https://en.wikipedia.org/wiki/Pope_John_Paul_II",
      },
      {
        slug: "mother-teresa",
        name: "Mother Teresa",
        saint_name: "Saint Teresa of Calcutta",
        birth_name: "Anjeze Gonxhe Bojaxhiu",
        birth_date: "1910-08-26",
        death_date: "1997-09-05",
        feast_day: "September 5",
        religious_order: "Missionaries of Charity",
        nationality: "Albanian / Indian",
        beatification_date: "2003-10-19",
        beatified_by: "Pope John Paul II",
        canonization_date: "2016-09-04",
        canonized_by: "Pope Francis",
        canonization_type: "confessor",
        canonization_stage: "saint",
        patronage: ["Missionaries of Charity", "poor and sick"],
        themes: ["conversion", "missionaries", "hope", "perseverance", "eucharistic"],
        biography_short: LOREM_BIO,
        gender: "female",
        lay_person: false,
        image_url: "https://upload.wikimedia.org/wikipedia/commons/8/8e/MotherTeresa_090.jpg",
        wikipedia_url: "https://en.wikipedia.org/wiki/Mother_Teresa",
      },
      {
        slug: "padre-pio",
        name: "Padre Pio",
        saint_name: "Saint Pio of Pietrelcina",
        birth_name: "Francesco Forgione",
        birth_date: "1887-05-25",
        death_date: "1968-09-23",
        feast_day: "September 23",
        religious_order: "Capuchin Franciscan",
        nationality: "Italian",
        beatification_date: "1999-05-02",
        beatified_by: "Pope John Paul II",
        canonization_date: "2002-06-16",
        canonized_by: "Pope John Paul II",
        canonization_type: "confessor",
        canonization_stage: "saint",
        patronage: ["stress relief", "civil defense volunteers", "adolescents"],
        themes: ["eucharistic", "marian", "spiritual-direction", "conversion", "perseverance"],
        biography_short: LOREM_BIO,
        gender: "male",
        lay_person: false,
        image_url: "https://upload.wikimedia.org/wikipedia/commons/5/51/Padre_Pio_portrait.jpg",
        wikipedia_url: "https://en.wikipedia.org/wiki/Padre_Pio",
      },
      {
        slug: "faustina-kowalska",
        name: "Faustina Kowalska",
        saint_name: "Saint Maria Faustina Kowalska",
        birth_name: "Helena Kowalska",
        birth_date: "1905-08-25",
        death_date: "1938-10-05",
        feast_day: "October 5",
        religious_order: "Congregation of the Sisters of Our Lady of Mercy",
        nationality: "Polish",
        beatification_date: "1993-04-18",
        beatified_by: "Pope John Paul II",
        canonization_date: "2000-04-30",
        canonized_by: "Pope John Paul II",
        canonization_type: "virgin",
        canonization_stage: "saint",
        patronage: ["Divine Mercy devotion", "sinners", "World Youth Day"],
        themes: ["conversion", "marian", "perseverance", "hope", "eucharistic"],
        biography_short: LOREM_BIO,
        gender: "female",
        lay_person: false,
        image_url:
          "https://upload.wikimedia.org/wikipedia/commons/0/0c/Saint_Faustyna_Kowalska_portrait_%281931%29.jpg",
        wikipedia_url: "https://en.wikipedia.org/wiki/Faustina_Kowalska",
      },
      {
        slug: "gianna-beretta-molla",
        name: "Gianna Beretta Molla",
        saint_name: "Saint Gianna Beretta Molla",
        birth_name: "Gianna Beretta Molla",
        birth_date: "1922-10-04",
        death_date: "1962-04-28",
        feast_day: "April 28",
        nationality: "Italian",
        beatification_date: "1994-04-24",
        beatified_by: "Pope John Paul II",
        canonization_date: "2004-05-16",
        canonized_by: "Pope John Paul II",
        canonization_type: "married_couple",
        canonization_stage: "saint",
        patronage: ["mothers", "families", "physicians", "unborn children"],
        themes: ["saints-of-everyday-life", "perseverance", "marian", "hope", "eucharistic"],
        biography_short: LOREM_BIO,
        gender: "female",
        lay_person: true,
        image_url: "https://upload.wikimedia.org/wikipedia/commons/8/87/GiannaBerettaMolla.jpg",
        wikipedia_url: "https://en.wikipedia.org/wiki/Gianna_Beretta_Molla",
      },
      {
        slug: "kateri-tekakwitha",
        name: "Kateri Tekakwitha",
        saint_name: "Saint Kateri Tekakwitha",
        birth_name: "Kateri Tekakwitha",
        birth_date: "1656-01-01",
        death_date: "1680-04-17",
        feast_day: "July 14",
        nationality: "Mohawk / Native American",
        beatification_date: "1980-06-22",
        beatified_by: "Pope John Paul II",
        canonization_date: "2012-10-21",
        canonized_by: "Pope Benedict XVI",
        canonization_type: "virgin",
        canonization_stage: "saint",
        patronage: ["Native Americans", "ecology", "environmentalists", "exiles"],
        themes: ["conversion", "marian", "missionaries", "perseverance", "hope"],
        biography_short: LOREM_BIO,
        gender: "female",
        lay_person: true,
        image_url: "https://upload.wikimedia.org/wikipedia/commons/1/14/Kateri_Tekakwitha_1690.jpg",
        wikipedia_url: "https://en.wikipedia.org/wiki/Kateri_Tekakwitha",
      },
      {
        slug: "andre-bessette",
        name: "Brother Andre",
        saint_name: "Saint Andre of Montreal",
        birth_name: "Andre Bessette",
        birth_date: "1845-08-09",
        death_date: "1937-01-06",
        feast_day: "January 6",
        religious_order: "Congregation of Holy Cross",
        nationality: "Canadian",
        beatification_date: "1982-05-23",
        beatified_by: "Pope John Paul II",
        canonization_date: "2010-10-17",
        canonized_by: "Pope Benedict XVI",
        canonization_type: "confessor",
        canonization_stage: "saint",
        patronage: ["The sick", "the grieving", "family caregivers"],
        themes: ["spiritual-direction", "eucharistic", "marian", "perseverance", "saints-of-everyday-life"],
        biography_short: LOREM_BIO,
        gender: "male",
        lay_person: false,
        image_url: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Fr%C3%A8re_Andr%C3%A9_1920.jpg",
        wikipedia_url: "https://en.wikipedia.org/wiki/Andre_Bessette",
      },
      {
        slug: "maximilian-kolbe",
        name: "Maximilian Kolbe",
        saint_name: "Saint Maximilian Kolbe",
        birth_name: "Rajmund Kolbe",
        birth_date: "1894-01-08",
        death_date: "1941-08-14",
        feast_day: "August 14",
        religious_order: "Conventual Franciscan",
        nationality: "Polish",
        beatification_date: "1971-10-17",
        beatified_by: "Pope Paul VI",
        canonization_date: "1982-10-10",
        canonized_by: "Pope John Paul II",
        canonization_type: "martyr",
        canonization_stage: "saint",
        patronage: ["addicts", "journalists", "prisoners", "families", "pro-life movement"],
        themes: ["martyrs", "marian", "perseverance", "conversion", "missionaries"],
        biography_short: LOREM_BIO,
        gender: "male",
        lay_person: false,
        image_url: "https://upload.wikimedia.org/wikipedia/commons/e/e9/Fr.Maximilian_Kolbe_1939.jpg",
        wikipedia_url: "https://en.wikipedia.org/wiki/Maximilian_Kolbe",
      },
      {
        slug: "louis-martin",
        name: "Louis Martin",
        saint_name: "Saint Louis Martin",
        birth_name: "Louis Martin",
        birth_date: "1823-08-22",
        death_date: "1894-07-29",
        feast_day: "July 12",
        nationality: "French",
        beatification_date: "2008-10-19",
        beatified_by: "Pope Benedict XVI",
        canonization_date: "2015-10-18",
        canonized_by: "Pope Francis",
        canonization_type: "married_couple",
        canonization_stage: "saint",
        patronage: ["married couples", "families", "parents", "Catholic families"],
        themes: ["saints-of-everyday-life", "conversion", "perseverance", "hope", "marian"],
        biography_short: LOREM_BIO,
        gender: "male",
        lay_person: true,
        image_url: "https://upload.wikimedia.org/wikipedia/commons/3/38/Louis_Martin_1.jpg",
        wikipedia_url: "https://en.wikipedia.org/wiki/Louis_Martin_and_Marie-Az%C3%A9lie_Gu%C3%A9rin",
      },
      {
        slug: "zelie-martin",
        name: "Zélie Martin",
        saint_name: "Saint Zélie Martin",
        birth_name: "Zelie Guerin Martin",
        birth_date: "1831-12-23",
        death_date: "1877-08-28",
        feast_day: "July 12",
        nationality: "French",
        beatification_date: "2008-10-19",
        beatified_by: "Pope Benedict XVI",
        canonization_date: "2015-10-18",
        canonized_by: "Pope Francis",
        canonization_type: "married_couple",
        canonization_stage: "saint",
        patronage: ["married couples", "families", "parents", "Catholic families"],
        themes: ["saints-of-everyday-life", "conversion", "perseverance", "hope", "marian"],
        biography_short: LOREM_BIO,
        gender: "female",
        lay_person: true,
        image_url: "https://upload.wikimedia.org/wikipedia/commons/a/a2/Z%C3%A9lie_Martin_1.jpg",
        wikipedia_url: "https://en.wikipedia.org/wiki/Louis_Martin_and_Marie-Az%C3%A9lie_Gu%C3%A9rin",
      },
      {
        slug: "carlo-acutis",
        name: "Carlo Acutis",
        saint_name: "Saint Carlo Acutis",
        birth_name: "Carlo Acutis",
        birth_date: "1991-05-03",
        death_date: "2006-10-12",
        feast_day: "October 12",
        nationality: "Italian",
        beatification_date: "2020-10-10",
        beatified_by: "Cardinal Agostino Vallini (Assisi)",
        canonization_date: "2025-09-07",
        canonized_by: "Pope Leo XIV",
        canonization_type: "confessor",
        canonization_stage: "saint",
        patronage: ["computer programmers", "internet users", "youth", "Eucharistic devotion"],
        themes: ["technology", "eucharistic", "conversion", "perseverance", "hope"],
        biography_short: `${LOREM_BIO}\n\n${CARLO_ACUTIS_BIO_NOTE}`,
        gender: "male",
        lay_person: true,
        wikipedia_url: "https://en.wikipedia.org/wiki/Carlo_Acutis",
      },
      {
        slug: "juan-diego",
        name: "Juan Diego",
        saint_name: "Saint Juan Diego",
        birth_name: "Juan Diego Cuauhtlatoatzin",
        birth_date: "1474-01-01",
        death_date: "1548-01-01",
        feast_day: "December 9",
        nationality: "Aztec / Indigenous Mexican",
        beatification_date: "1990-05-06",
        beatified_by: "Pope John Paul II (equipollent)",
        canonization_date: "2002-07-31",
        canonized_by: "Pope John Paul II",
        canonization_type: "confessor",
        canonization_stage: "saint",
        patronage: ["indigenous peoples of the Americas"],
        themes: ["conversion", "marian", "perseverance", "hope", "saints-of-everyday-life"],
        biography_short: LOREM_BIO,
        gender: "male",
        lay_person: true,
        image_url: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Juan-Diego.jpg",
        wikipedia_url: "https://en.wikipedia.org/wiki/Juan_Diego",
      },
    ])
    .returning({ id: schema.saints.id, slug: schema.saints.slug });

  console.log(`Inserted ${insertedSaints.length} saints.`);

  const saintId = (slug: string) => {
    const s = insertedSaints.find((r) => r.slug === slug);
    if (!s) throw new Error(`Saint not found: ${slug}`);
    return s.id;
  };

  console.log("Seeding saint relations...");

  await db.insert(schema.saintRelations).values([
    {
      saint_id: saintId("louis-martin"),
      related_saint_id: saintId("zelie-martin"),
      relation_type: "canonized_together",
    },
    {
      saint_id: saintId("zelie-martin"),
      related_saint_id: saintId("louis-martin"),
      relation_type: "canonized_together",
    },
  ]);

  console.log("Seeding miracles...");

  const insertedMiracles = await db
    .insert(schema.miracles)
    .values([
      // ── John Paul II ──────────────────────────────────────────────────────────
      {
        slug: "healing-of-sr-marie-simon-pierre",
        title: "Healing of Sr. Marie Simon-Pierre",
        miracle_category: "intercessory",
        type: "healing",
        topics: ["elderly", "mothers", "pro-life"],
        date_of_event: "2005-06-02",
        date_precision: "exact_day",
        timing_relative_to_saint_death: "posthumous",
        location_name: "Aix-en-Provence",
        location_lat: "43.5298424",
        location_lng: "5.4474738",
        country: "France",
        recipient_name: "Sr. Marie Simon-Pierre",
        recipient_gender: "female",
        recipient_country: "France",
        recipient_privacy: "public",
        medical_diagnosis: "Parkinson's disease (diagnosed 2001)",
        cure_details:
          "Severe Parkinson's — could not write or drive. On the night of June 2, she felt compelled to write JPII's name and found her hand steady. Complete recovery.",
        cure_characteristics: "instant_complete",
        was_medically_verified: true,
        medical_verification_date: "2009-01-01",
        intercessory_medium: "prayer_only",
        vatican_recognized: true,
        vatican_medical_board_verdict: "Declared medically inexplicable in 2009",
        used_for_beatification: true,
        used_for_canonization: false,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },
      {
        slug: "healing-of-floribeth-mora-diaz",
        title: "Healing of Floribeth Mora Diaz",
        miracle_category: "intercessory",
        type: "healing",
        topics: ["mothers"],
        date_of_event: "2011-05-01",
        date_precision: "exact_day",
        timing_relative_to_saint_death: "posthumous",
        location_name: "Costa Rica (home)",
        location_lat: "9.9327707",
        location_lng: "-84.0796144",
        country: "Costa Rica",
        recipient_name: "Floribeth Mora Diaz",
        recipient_gender: "female",
        recipient_country: "Costa Rica",
        recipient_privacy: "public",
        medical_diagnosis: "Severe brain aneurysm (diagnosed April 2011, terminal, sent home to die)",
        cure_details:
          "While watching JPII's beatification on TV, she heard his voice say \"Don't be afraid. I am with you.\" She felt immediate improvement.",
        cure_characteristics: "instant_complete",
        was_medically_verified: true,
        medical_verification_date: "2013-01-01",
        intercessory_medium: "prayer_only",
        vatican_recognized: true,
        vatican_medical_board_verdict: "Declared medically inexplicable in 2013",
        used_for_beatification: false,
        used_for_canonization: true,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },

      // ── Mother Teresa ─────────────────────────────────────────────────────────
      {
        slug: "healing-of-monica-besra",
        title: "Healing of Monica Besra",
        miracle_category: "intercessory",
        type: "healing",
        topics: ["mothers", "financial-hardship"],
        date_of_event: "1998-09-05",
        date_precision: "exact_day",
        timing_relative_to_saint_death: "posthumous",
        location_name: "Nadia district, West Bengal",
        location_lat: "23.4847374",
        location_lng: "88.5567067",
        country: "India",
        region: "West Bengal",
        recipient_name: "Monica Besra",
        recipient_gender: "female",
        recipient_country: "India",
        recipient_privacy: "public",
        medical_diagnosis: "Large benign abdominal/ovarian tumor",
        cure_details:
          "After applying a medallion of Mother Teresa and praying, she felt intense warmth and the tumor disappeared.",
        cure_characteristics: "instant_complete",
        was_medically_verified: true,
        medical_verification_date: "2002-01-01",
        intercessory_medium: "medallion",
        vatican_recognized: true,
        vatican_medical_board_verdict: "Declared medically inexplicable in 2002",
        used_for_beatification: true,
        used_for_canonization: false,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },
      {
        slug: "healing-of-marcilio-haddad-andrino",
        title: "Healing of Marcilio Haddad Andrino",
        miracle_category: "intercessory",
        type: "healing",
        topics: [],
        date_of_event: "2008-12-09",
        date_precision: "exact_day",
        timing_relative_to_saint_death: "posthumous",
        location_name: "Santos",
        location_lat: "-23.9609448",
        location_lng: "-46.3166316",
        country: "Brazil",
        region: "Sao Paulo",
        recipient_name: "Marcilio Haddad Andrino",
        recipient_gender: "male",
        recipient_country: "Brazil",
        recipient_privacy: "public",
        medical_diagnosis: "Multiple brain abscesses / viral meningoencephalitis with hydrocephalus",
        cure_details:
          "In a coma, on life support, family told to prepare for his death. His wife prayed with a relic. Doctors found him conscious the next morning with all symptoms gone.",
        cure_characteristics: "instant_complete",
        was_medically_verified: true,
        medical_verification_date: "2015-01-01",
        intercessory_medium: "relic",
        vatican_recognized: true,
        vatican_medical_board_verdict: "Declared medically inexplicable in 2015",
        used_for_beatification: false,
        used_for_canonization: true,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },

      // ── Padre Pio ─────────────────────────────────────────────────────────────
      {
        slug: "healing-of-consiglia-de-martino",
        title: "Healing of Consiglia De Martino",
        miracle_category: "intercessory",
        type: "healing",
        topics: ["elderly", "children"],
        date_of_event: "1958-10-07",
        date_precision: "exact_day",
        timing_relative_to_saint_death: "during_lifetime",
        location_name: "Salerno",
        location_lat: "40.4194416",
        location_lng: "15.3106085",
        country: "Italy",
        recipient_name: "Consiglia De Martino",
        recipient_gender: "female",
        recipient_country: "Italy",
        recipient_privacy: "public",
        medical_diagnosis: "Ruptured stomach / severe peritonitis from burst appendix",
        cure_details:
          "Near death after botched surgery. Father brought a photo of Padre Pio to her hospital room. She saw a vision of a Capuchin friar who said \"Don't you know I only work at night?\" Healed instantly.",
        cure_characteristics: "instant_complete",
        was_medically_verified: true,
        intercessory_medium: "saint_image",
        vatican_recognized: true,
        vatican_medical_board_verdict: "Declared medically inexplicable",
        used_for_beatification: true,
        used_for_canonization: false,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },
      {
        slug: "healing-of-matteo-pio-colella",
        title: "Healing of Matteo Pio Colella",
        miracle_category: "intercessory",
        type: "healing",
        topics: ["children"],
        date_of_event: "2000-07-21",
        date_precision: "exact_day",
        timing_relative_to_saint_death: "posthumous",
        location_name: "San Giovanni Rotondo",
        location_lat: "41.7069106",
        location_lng: "15.7288455",
        country: "Italy",
        recipient_name: "Matteo Pio Colella",
        recipient_gender: "male",
        recipient_country: "Italy",
        recipient_privacy: "public",
        recipient_age_at_event: 7,
        medical_diagnosis: "Coma after meningitis, severe brain damage, multiple organ failure",
        cure_details:
          "The 7-year-old was dying. His mother prayed intensely at Padre Pio's tomb. He recovered fully with no brain damage.",
        cure_characteristics: "instant_complete",
        was_medically_verified: true,
        intercessory_medium: "tomb_prayer",
        vatican_recognized: true,
        vatican_medical_board_verdict: "Declared medically inexplicable",
        used_for_beatification: false,
        used_for_canonization: true,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },
      {
        slug: "stigmata-of-padre-pio",
        title: "The Stigmata of Padre Pio",
        miracle_category: "associated",
        type: "stigmata",
        topics: [],
        date_of_event: "1918-09-20",
        date_precision: "exact_day",
        timing_relative_to_saint_death: "during_lifetime",
        location_name: "San Giovanni Rotondo",
        location_lat: "41.7069106",
        location_lng: "15.7288455",
        country: "Italy",
        recipient_gender: "not_applicable",
        recipient_privacy: "not_applicable",
        cure_details:
          "Received visible stigmata (wounds of Christ) on hands, feet, and side. Visible for 50 years until his death. Examined by multiple doctors, Vatican investigators, and photographers. Remained fresh and never became infected despite no treatment.",
        cure_characteristics: "not_applicable",
        was_medically_verified: true,
        intercessory_medium: "not_applicable",
        vatican_recognized: true,
        vatican_medical_board_verdict: "Vatican commission (1925) declared wounds not of natural origin",
        used_for_beatification: false,
        used_for_canonization: false,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },
      {
        slug: "bilocation-of-padre-pio",
        title: "Bilocation of Padre Pio",
        miracle_category: "associated",
        type: "bilocation",
        topics: [],
        date_precision: "century",
        timing_relative_to_saint_death: "during_lifetime",
        location_name: "Multiple locations worldwide",
        country: "Italy",
        recipient_gender: "not_applicable",
        recipient_privacy: "not_applicable",
        cure_details:
          "Numerous documented accounts of Padre Pio appearing in two places simultaneously. Often reported during WWII when soldiers saw him on battlefields, only to learn he was at the monastery in Italy. Also reported in confessionals, during Mass, and at bedsides of the dying.",
        cure_characteristics: "not_applicable",
        was_medically_verified: false,
        intercessory_medium: "not_applicable",
        vatican_recognized: true,
        used_for_beatification: false,
        used_for_canonization: false,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },

      // ── Faustina Kowalska ─────────────────────────────────────────────────────
      {
        slug: "healing-of-maureen-digan",
        title: "Healing of Maureen Digan",
        miracle_category: "intercessory",
        type: "healing",
        topics: ["mothers", "elderly"],
        date_of_event: "1981-03-13",
        date_precision: "exact_day",
        timing_relative_to_saint_death: "posthumous",
        location_name: "Fall River, Massachusetts",
        location_lat: "41.7010642",
        location_lng: "-71.1546367",
        country: "USA",
        region: "Massachusetts",
        recipient_name: "Maureen Digan",
        recipient_gender: "female",
        recipient_country: "USA",
        recipient_privacy: "public",
        medical_diagnosis: "Lymphedema (chronic, severe leg swelling, unable to walk for 36 years)",
        cure_details:
          "While visiting St. Faustina's tomb in Poland, prayed and felt a cracking sensation. Swelling drained immediately and she could walk.",
        cure_characteristics: "instant_complete",
        was_medically_verified: true,
        medical_verification_date: "1992-01-01",
        intercessory_medium: "tomb_prayer",
        vatican_recognized: true,
        vatican_medical_board_verdict: "Declared medically inexplicable in 1992",
        used_for_beatification: true,
        used_for_canonization: false,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },
      {
        slug: "healing-of-fr-ronald-pytel",
        title: "Healing of Fr. Ronald Pytel",
        miracle_category: "intercessory",
        type: "healing",
        topics: [],
        date_of_event: "1995-10-01",
        date_precision: "month",
        timing_relative_to_saint_death: "posthumous",
        location_name: "Baltimore, Maryland",
        location_lat: "39.2908816",
        location_lng: "-76.6107590",
        country: "USA",
        region: "Maryland",
        recipient_name: "Fr. Ronald Pytel",
        recipient_gender: "male",
        recipient_country: "Poland",
        recipient_privacy: "public",
        medical_diagnosis: "Advanced arteriosclerosis, severe angina (needed bypass surgery)",
        cure_details:
          "Told he needed bypass surgery. After praying to Faustina, symptoms disappeared and medical tests showed a normal heart.",
        cure_characteristics: "instant_complete",
        was_medically_verified: true,
        medical_verification_date: "1999-01-01",
        intercessory_medium: "prayer_only",
        vatican_recognized: true,
        vatican_medical_board_verdict: "Declared medically inexplicable in 1999",
        used_for_beatification: false,
        used_for_canonization: true,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },
      {
        slug: "divine-mercy-revelations",
        title: "Divine Mercy Revelations to St. Faustina",
        miracle_category: "associated",
        type: "apparition",
        topics: [],
        date_of_event: "1931-01-01",
        date_precision: "decade",
        timing_relative_to_saint_death: "during_lifetime",
        location_name: "Krakow and Vilnius (convents)",
        location_lat: "50.0469432",
        location_lng: "19.9971534",
        country: "Poland",
        recipient_name: "St. Faustina Kowalska",
        recipient_gender: "female",
        recipient_country: "Poland",
        recipient_privacy: "public",
        cure_details:
          "Multiple visions of Jesus Christ beginning February 22, 1931. Jesus appeared with rays of red and white light, instructing Faustina to have an image painted (\"Jesus, I trust in You\"). Dictated the Chaplet of Divine Mercy and established Divine Mercy Sunday. Faustina recorded everything in her Diary (600+ pages), later approved by the Vatican.",
        cure_characteristics: "not_applicable",
        was_medically_verified: false,
        intercessory_medium: "not_applicable",
        vatican_recognized: true,
        vatican_decree_date: "2000-01-01",
        used_for_beatification: false,
        used_for_canonization: false,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },

      // ── Gianna Beretta Molla ───────────────────────────────────────────────────
      {
        slug: "healing-of-lucia-sylvia-cirilo",
        title: "Healing of Lucia Sylvia Cirilo",
        miracle_category: "intercessory",
        type: "healing",
        topics: ["mothers", "pregnancy-and-childbirth"],
        date_of_event: "1977-11-09",
        date_precision: "exact_day",
        timing_relative_to_saint_death: "posthumous",
        location_name: "Saint Francis of Assisi Hospital, Grajau",
        location_lat: "-5.8154034",
        location_lng: "-46.1361454",
        country: "Brazil",
        region: "Maranhao",
        recipient_name: "Lucia Sylvia Cirilo",
        recipient_gender: "female",
        recipient_country: "Brazil",
        recipient_privacy: "public",
        medical_diagnosis: "Recto-vaginal fistula (after stillbirth on October 22, 1977; hospital unequipped to treat)",
        cure_details:
          "After a stillbirth, Cirilo developed a severe recto-vaginal fistula. The hospital could not treat it and she was told she needed to be transferred, but believed she would not survive the trip. A nurse, Sister Bernardina de Manaus, prayed for Gianna's intercession. The next morning, Cirilo's pain had vanished and the fistula had healed completely without surgery.",
        cure_characteristics: "instant_complete",
        was_medically_verified: true,
        intercessory_medium: "prayer_only",
        vatican_recognized: true,
        vatican_medical_board_verdict: "Declared medically inexplicable",
        used_for_beatification: true,
        used_for_canonization: false,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },
      {
        slug: "healing-of-elizabeth-comparini-arcolino",
        title: "Healing of Elizabeth Comparini Arcolino",
        miracle_category: "intercessory",
        type: "healing",
        topics: ["pregnancy-and-childbirth", "mothers", "children", "pro-life"],
        date_of_event: "2000-01-01",
        date_precision: "year",
        timing_relative_to_saint_death: "posthumous",
        country: "Brazil",
        recipient_name: "Elizabeth Comparini Arcolino",
        recipient_gender: "female",
        recipient_country: "Brazil",
        recipient_privacy: "public",
        medical_diagnosis:
          "Placental tear at 16 weeks of pregnancy, complete loss of amniotic fluid; doctors said child's survival impossible",
        cure_details:
          "At 16 weeks pregnant, Arcolino sustained a tear in her placenta that drained all amniotic fluid. Doctors told her the child had no chance of survival. She prayed for Gianna's intercession and delivered a healthy baby girl, Gianna Maria, via C-section. The recovery was deemed medically inexplicable.",
        cure_characteristics: "gradual_complete",
        was_medically_verified: true,
        intercessory_medium: "prayer_only",
        vatican_recognized: true,
        vatican_medical_board_verdict: "Declared medically inexplicable",
        used_for_beatification: false,
        used_for_canonization: true,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },

      // ── Kateri Tekakwitha ─────────────────────────────────────────────────────
      {
        slug: "healing-of-native-american-boy",
        title: "Healing of an Unnamed Native American Boy",
        miracle_category: "intercessory",
        type: "healing",
        topics: ["children", "native-and-indigenous"],
        date_of_event: "1940-01-01",
        date_precision: "decade",
        timing_relative_to_saint_death: "posthumous",
        country: "USA",
        recipient_gender: "male",
        recipient_country: "USA",
        recipient_privacy: "confidential",
        medical_diagnosis: "Severe illness (records not publicly detailed)",
        cure_details: "Healed through prayer to Kateri.",
        cure_characteristics: "instant_complete",
        was_medically_verified: true,
        intercessory_medium: "prayer_only",
        vatican_recognized: true,
        used_for_beatification: true,
        used_for_canonization: false,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: false,
      },
      {
        slug: "healing-of-jake-finkbonner",
        title: "Healing of Jake Finkbonner",
        miracle_category: "intercessory",
        type: "healing",
        topics: ["children", "native-and-indigenous"],
        date_of_event: "2006-01-01",
        date_precision: "year",
        timing_relative_to_saint_death: "posthumous",
        location_name: "Ferndale, Washington",
        location_lat: "48.8466698",
        location_lng: "-122.5897230",
        country: "USA",
        region: "Washington",
        recipient_name: "Jake Finkbonner",
        recipient_gender: "male",
        recipient_country: "USA",
        recipient_privacy: "public",
        recipient_age_at_event: 6,
        medical_diagnosis: "Necrotizing fasciitis (flesh-eating bacteria) from facial injury",
        cure_details:
          "Infection spreading rapidly, doctors said he would die or require extensive facial disfigurement. Relic of Kateri applied, prayers offered. Infection stopped, fully recovered without scarring.",
        cure_characteristics: "instant_complete",
        was_medically_verified: true,
        intercessory_medium: "relic",
        vatican_recognized: true,
        vatican_medical_board_verdict: "Declared medically inexplicable",
        used_for_beatification: false,
        used_for_canonization: true,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },
      {
        slug: "vanishing-of-smallpox-scars",
        title: "Vanishing of Smallpox Scars at Death",
        miracle_category: "associated",
        type: "other",
        topics: ["native-and-indigenous"],
        date_of_event: "1680-04-17",
        date_precision: "exact_day",
        timing_relative_to_saint_death: "during_lifetime",
        location_name: "Kahnawake, Quebec",
        location_lat: "45.4147888",
        location_lng: "-73.6773614",
        country: "Canada",
        region: "Quebec",
        recipient_name: "St. Kateri Tekakwitha",
        recipient_gender: "female",
        recipient_country: "Canada",
        recipient_privacy: "public",
        recipient_age_at_event: 24,
        medical_diagnosis:
          "Smallpox scarring (survived epidemic at age 4, left with facial scarring and impaired vision)",
        cure_details:
          "Moments after her death, witnesses observed that the smallpox scars that had marked Kateri's face since childhood completely vanished. Her skin became smooth and beautiful. Witnessed by multiple people present at her deathbed and cited in her canonization process.",
        cure_characteristics: "not_applicable",
        was_medically_verified: false,
        intercessory_medium: "not_applicable",
        vatican_recognized: true,
        used_for_beatification: false,
        used_for_canonization: false,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },

      // ── André Bessette ────────────────────────────────────────────────────────
      {
        slug: "healing-of-giuseppe-carlo-audino",
        title: "Healing of Giuseppe Carlo Audino",
        miracle_category: "intercessory",
        type: "healing",
        topics: ["elderly"],
        date_of_event: "1958-01-01",
        date_precision: "year",
        timing_relative_to_saint_death: "posthumous",
        location_name: "Rochester",
        location_lat: "43.1572850",
        location_lng: "-77.6152140",
        country: "USA",
        region: "New York",
        recipient_name: "Giuseppe Carlo Audino",
        recipient_gender: "male",
        recipient_country: "USA",
        recipient_privacy: "public",
        medical_diagnosis: "Severe liver cancer (terminal, given only palliative care)",
        cure_details:
          "Doctors provided only palliative care. After prayers to Brother Andre, Audino was cured nearly overnight. The rapid and complete remission was deemed medically inexplicable.",
        cure_characteristics: "instant_complete",
        was_medically_verified: true,
        intercessory_medium: "prayer_only",
        vatican_recognized: true,
        vatican_medical_board_verdict: "Declared medically inexplicable",
        used_for_beatification: true,
        used_for_canonization: false,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },
      {
        slug: "healing-of-child-traumatic-brain-injury",
        title: "Healing of a Child from Traumatic Brain Injury",
        miracle_category: "intercessory",
        type: "healing",
        topics: ["children"],
        date_of_event: "1999-01-01",
        date_precision: "year",
        timing_relative_to_saint_death: "posthumous",
        country: "Canada",
        recipient_gender: "male",
        recipient_country: "Canada",
        recipient_privacy: "confidential",
        recipient_age_at_event: 9,
        medical_diagnosis:
          "Severe traumatic brain injury from bicycle accident, fell into coma, given little hope of recovery",
        cure_details:
          "A 9-year-old child suffered a traumatic brain injury in a bicycle accident and fell into a coma. After prayers to Brother Andre, the child experienced a rapid and complete recovery deemed scientifically impossible by medical experts and theologians.",
        cure_characteristics: "instant_complete",
        was_medically_verified: true,
        intercessory_medium: "prayer_only",
        vatican_recognized: true,
        vatican_decree_date: "2009-12-19",
        vatican_medical_board_verdict: "Declared medically inexplicable",
        used_for_beatification: false,
        used_for_canonization: true,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },

      // ── Maximilian Kolbe ──────────────────────────────────────────────────────
      // Canonized as martyr — no canonization miracle required; both miracles are for beatification.
      {
        slug: "healing-of-angela-testoni",
        title: "Healing of Angela Testoni",
        miracle_category: "intercessory",
        type: "healing",
        topics: ["elderly"],
        date_of_event: "1948-07-01",
        date_precision: "month",
        timing_relative_to_saint_death: "posthumous",
        country: "Italy",
        recipient_name: "Angela Testoni",
        recipient_gender: "female",
        recipient_country: "Italy",
        recipient_privacy: "public",
        medical_diagnosis: "Intestinal tuberculosis (advanced, considered terminal)",
        cure_details:
          "Angela Testoni was cured of advanced intestinal tuberculosis in July 1948 after praying for Maximilian Kolbe's intercession. The cure was accepted as one of two miracles for his beatification.",
        cure_characteristics: "instant_complete",
        was_medically_verified: true,
        intercessory_medium: "prayer_only",
        vatican_recognized: true,
        vatican_medical_board_verdict: "Declared medically inexplicable",
        used_for_beatification: true,
        used_for_canonization: false,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },
      {
        slug: "healing-of-francis-ranier",
        title: "Healing of Francis Ranier",
        miracle_category: "intercessory",
        type: "healing",
        topics: ["elderly"],
        date_of_event: "1950-08-01",
        date_precision: "month",
        timing_relative_to_saint_death: "posthumous",
        country: "Italy",
        recipient_name: "Francis Ranier",
        recipient_gender: "male",
        recipient_country: "Italy",
        recipient_privacy: "public",
        medical_diagnosis: "Calcification of arterial sclerosis (severe cardiovascular condition)",
        cure_details:
          "Francis Ranier was cured of severe calcification of the arterial sclerosis in August 1950 after praying for Maximilian Kolbe's intercession. The cure was accepted as the second of two miracles for his beatification.",
        cure_characteristics: "instant_complete",
        was_medically_verified: true,
        intercessory_medium: "prayer_only",
        vatican_recognized: true,
        vatican_medical_board_verdict: "Declared medically inexplicable",
        used_for_beatification: true,
        used_for_canonization: false,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },

      // ── Louis & Zélie Martin ──────────────────────────────────────────────────
      {
        slug: "healing-of-pietro-schiliro",
        title: "Healing of Pietro Schiliro",
        miracle_category: "intercessory",
        type: "healing",
        topics: ["children"],
        date_of_event: "2007-01-01",
        date_precision: "year",
        timing_relative_to_saint_death: "posthumous",
        country: "Italy",
        recipient_name: "Pietro Schiliro",
        recipient_gender: "male",
        recipient_country: "Italy",
        recipient_privacy: "first_name_only",
        recipient_age_at_event: 0,
        medical_diagnosis: "Severe lung trouble (respiratory condition, near death)",
        cure_details:
          "An Italian child suffering from a severe, life-threatening lung condition was cured through the intercession of Louis and Zelie Martin. The cure was recognized by the Catholic Church a few months before their beatification.",
        cure_characteristics: "instant_complete",
        was_medically_verified: true,
        intercessory_medium: "prayer_only",
        vatican_recognized: true,
        vatican_decree_date: "2008-01-01",
        vatican_medical_board_verdict: "Declared medically inexplicable",
        used_for_beatification: true,
        used_for_canonization: false,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },
      {
        slug: "healing-of-carmen-valencia",
        title: "Healing of Carmen (infant born in Valencia)",
        miracle_category: "intercessory",
        type: "healing",
        topics: ["children", "mothers"],
        date_of_event: "2008-01-01",
        date_precision: "year",
        timing_relative_to_saint_death: "posthumous",
        location_name: "Valencia",
        location_lat: "39.4697065",
        location_lng: "-0.3763353",
        country: "Spain",
        region: "Valencia",
        recipient_name: "Carmen",
        recipient_gender: "female",
        recipient_country: "Spain",
        recipient_privacy: "first_name_only",
        recipient_age_at_event: 0,
        medical_diagnosis: "Severe medical condition at birth (eight doctors testified no scientific explanation for her cure)",
        cure_details:
          "Carmen was born in Valencia four days before Louis and Zelie's beatification (October 19, 2008). She suffered from a severe condition at birth, and eight doctors testified that there was no scientific explanation for her recovery. The miracle was accepted by the Congregation for the Causes of Saints on March 18, 2015.",
        cure_characteristics: "instant_complete",
        was_medically_verified: true,
        medical_verification_date: "2013-01-01",
        intercessory_medium: "prayer_only",
        vatican_recognized: true,
        vatican_decree_date: "2015-03-18",
        vatican_medical_board_verdict: "Eight doctors testified no scientific explanation for the cure",
        used_for_beatification: false,
        used_for_canonization: true,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },

      // ── Carlo Acutis ──────────────────────────────────────────────────────────
      {
        slug: "healing-of-matheus",
        title: "Healing of Matheus (Pancreatic Disease)",
        miracle_category: "intercessory",
        type: "healing",
        topics: ["children", "youth"],
        date_of_event: "2013-10-01",
        date_precision: "month",
        timing_relative_to_saint_death: "posthumous",
        location_name: "Campo Grande",
        location_lat: "-20.4640173",
        location_lng: "-54.6162947",
        country: "Brazil",
        recipient_name: "Matheus Vianna",
        recipient_gender: "male",
        recipient_country: "Brazil",
        recipient_privacy: "first_name_only",
        medical_diagnosis: "Rare pancreatic disease (possibly annular pancreas)",
        cure_details:
          "Mother prayed to Carlo after learning about his story. Doctors said surgery was only option. Boy recovered spontaneously.",
        cure_characteristics: "instant_complete",
        was_medically_verified: true,
        intercessory_medium: "prayer_only",
        vatican_recognized: true,
        vatican_medical_board_verdict: "Declared medically inexplicable",
        used_for_beatification: true,
        used_for_canonization: false,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },
      {
        slug: "healing-of-valeria-valverde",
        title: "Healing of Valeria Valverde",
        miracle_category: "intercessory",
        type: "healing",
        topics: ["youth", "mothers"],
        date_of_event: "2022-07-01",
        date_precision: "month",
        timing_relative_to_saint_death: "posthumous",
        location_name: "Florence",
        location_lat: "43.7697955",
        location_lng: "11.2556404",
        country: "Italy",
        region: "Tuscany",
        recipient_name: "Valeria Valverde",
        recipient_gender: "female",
        recipient_country: "Costa Rica",
        recipient_privacy: "public",
        medical_diagnosis: "Brain haemorrhage from falling off a bicycle; doctors gave low chance of survival",
        cure_details:
          "Mother Lilliana prayed for Carlo's intercession and visited his tomb in Assisi. Same day, Valeria began breathing independently. Next day, she was able to walk with all evidence of the haemorrhage having disappeared.",
        cure_characteristics: "instant_complete",
        was_medically_verified: true,
        intercessory_medium: "tomb_prayer",
        vatican_recognized: true,
        vatican_decree_date: "2024-05-23",
        vatican_medical_board_verdict:
          "Recognized as second miracle by Pope Francis on May 23, 2024; canonized Sept 7, 2025",
        used_for_beatification: false,
        used_for_canonization: true,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },

      // ── Juan Diego ────────────────────────────────────────────────────────────
      {
        slug: "healing-of-juan-jose-barragan-silva",
        title: "Healing of Juan José Barragán Silva",
        miracle_category: "intercessory",
        type: "healing",
        topics: ["addiction", "youth"],
        date_of_event: "1990-05-03",
        date_precision: "exact_day",
        timing_relative_to_saint_death: "posthumous",
        location_name: "Queretaro",
        location_lat: "20.8052225",
        location_lng: "-99.8837376",
        country: "Mexico",
        recipient_name: "Juan José Barragán Silva",
        recipient_gender: "male",
        recipient_country: "Mexico",
        recipient_privacy: "public",
        recipient_age_at_event: 20,
        medical_diagnosis:
          "Severe trauma from 10m head-first fall: spinal/neck/cranial fractures, intracranial hemorrhage",
        cure_details:
          "20-year-old drug addict fell 10 meters head-first from an apartment balcony onto cement in an apparent suicide attempt. His mother, who witnessed the fall, invoked Juan Diego. He went into a coma and emerged on May 6 — the same day Pope John Paul II celebrated Juan Diego's beatification. A week later he was sufficiently recovered to be discharged. Five medical consultors unanimously declared the cure medically inexplicable in 1998.",
        cure_characteristics: "instant_complete",
        was_medically_verified: true,
        medical_verification_date: "1998-01-01",
        intercessory_medium: "prayer_only",
        vatican_recognized: true,
        vatican_decree_date: "2001-12-20",
        vatican_medical_board_verdict:
          "5 consultors unanimous medically inexplicable (1998); theological board unanimous (May 2001); decree signed Dec 20, 2001",
        used_for_beatification: false,
        used_for_canonization: true,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },
      {
        slug: "tilma-of-guadalupe",
        title: "The Tilma of Our Lady of Guadalupe",
        miracle_category: "associated",
        type: "miraculous_image",
        topics: ["native-and-indigenous"],
        date_of_event: "1531-12-09",
        date_precision: "exact_day",
        timing_relative_to_saint_death: "during_lifetime",
        location_name: "Tepeyac Hill",
        location_lat: "19.4848583",
        location_lng: "-99.1178571",
        country: "Mexico",
        region: "Mexico City",
        recipient_gender: "not_applicable",
        recipient_privacy: "not_applicable",
        cure_details:
          "Our Lady appeared to Juan Diego. Bishop demanded a sign. Juan Diego gathered Castilian roses (out of season) in his tilma. When opened before the bishop, the image of Our Lady was miraculously imprinted on the fabric.",
        cure_characteristics: "not_applicable",
        was_medically_verified: false,
        intercessory_medium: "not_applicable",
        vatican_recognized: true,
        used_for_beatification: false,
        used_for_canonization: false,
        synopsis: LOREM_SYNOPSIS,
        has_primary_sources: true,
      },
    ])
    .returning({ id: schema.miracles.id, slug: schema.miracles.slug });

  console.log(`Inserted ${insertedMiracles.length} miracles.`);

  const miracleId = (slug: string) => {
    const m = insertedMiracles.find((r) => r.slug === slug);
    if (!m) throw new Error(`Miracle not found: ${slug}`);
    return m.id;
  };

  console.log("Seeding miracle saints...");

  await db.insert(schema.miracleSaints).values([
    // John Paul II
    { miracle_id: miracleId("healing-of-sr-marie-simon-pierre"), saint_id: saintId("john-paul-ii") },
    { miracle_id: miracleId("healing-of-floribeth-mora-diaz"), saint_id: saintId("john-paul-ii") },
    // Mother Teresa
    { miracle_id: miracleId("healing-of-monica-besra"), saint_id: saintId("mother-teresa") },
    { miracle_id: miracleId("healing-of-marcilio-haddad-andrino"), saint_id: saintId("mother-teresa") },
    // Padre Pio
    { miracle_id: miracleId("healing-of-consiglia-de-martino"), saint_id: saintId("padre-pio") },
    { miracle_id: miracleId("healing-of-matteo-pio-colella"), saint_id: saintId("padre-pio") },
    { miracle_id: miracleId("stigmata-of-padre-pio"), saint_id: saintId("padre-pio") },
    { miracle_id: miracleId("bilocation-of-padre-pio"), saint_id: saintId("padre-pio") },
    // Faustina Kowalska
    { miracle_id: miracleId("healing-of-maureen-digan"), saint_id: saintId("faustina-kowalska") },
    { miracle_id: miracleId("healing-of-fr-ronald-pytel"), saint_id: saintId("faustina-kowalska") },
    { miracle_id: miracleId("divine-mercy-revelations"), saint_id: saintId("faustina-kowalska") },
    // Gianna Beretta Molla
    { miracle_id: miracleId("healing-of-lucia-sylvia-cirilo"), saint_id: saintId("gianna-beretta-molla") },
    { miracle_id: miracleId("healing-of-elizabeth-comparini-arcolino"), saint_id: saintId("gianna-beretta-molla") },
    // Kateri Tekakwitha
    { miracle_id: miracleId("healing-of-native-american-boy"), saint_id: saintId("kateri-tekakwitha") },
    { miracle_id: miracleId("healing-of-jake-finkbonner"), saint_id: saintId("kateri-tekakwitha") },
    { miracle_id: miracleId("vanishing-of-smallpox-scars"), saint_id: saintId("kateri-tekakwitha") },
    // Andre Bessette
    { miracle_id: miracleId("healing-of-giuseppe-carlo-audino"), saint_id: saintId("andre-bessette") },
    { miracle_id: miracleId("healing-of-child-traumatic-brain-injury"), saint_id: saintId("andre-bessette") },
    // Maximilian Kolbe
    { miracle_id: miracleId("healing-of-angela-testoni"), saint_id: saintId("maximilian-kolbe") },
    { miracle_id: miracleId("healing-of-francis-ranier"), saint_id: saintId("maximilian-kolbe") },
    // Louis & Zélie Martin — both miracles attributed to both saints jointly
    { miracle_id: miracleId("healing-of-pietro-schiliro"), saint_id: saintId("louis-martin") },
    { miracle_id: miracleId("healing-of-pietro-schiliro"), saint_id: saintId("zelie-martin") },
    { miracle_id: miracleId("healing-of-carmen-valencia"), saint_id: saintId("louis-martin") },
    { miracle_id: miracleId("healing-of-carmen-valencia"), saint_id: saintId("zelie-martin") },
    // Carlo Acutis
    { miracle_id: miracleId("healing-of-matheus"), saint_id: saintId("carlo-acutis") },
    { miracle_id: miracleId("healing-of-valeria-valverde"), saint_id: saintId("carlo-acutis") },
    // Juan Diego
    { miracle_id: miracleId("healing-of-juan-jose-barragan-silva"), saint_id: saintId("juan-diego") },
    { miracle_id: miracleId("tilma-of-guadalupe"), saint_id: saintId("juan-diego") },
  ]);

  console.log("Seeding miracle sources...");

  await db.insert(schema.miracleSources).values([
    // John Paul II - M1
    {
      miracle_id: miracleId("healing-of-sr-marie-simon-pierre"),
      url: "https://www.catholicnewsagency.com/news/the-miracle-that-led-to-john-paul-ii-beatification-12766",
      title: "The miracle that led to John Paul II's beatification - CNA",
      source_type: "news_article",
    },
    // John Paul II - M2
    {
      miracle_id: miracleId("healing-of-floribeth-mora-diaz"),
      url: "https://www.ewtnnews.com/world/europe/woman-healed-by-john-paul-iis-intercession-recounts-miracle",
      title: "Woman healed by John Paul II's intercession recounts miracle - EWTN News",
      source_type: "news_article",
    },
    // Mother Teresa - M1
    {
      miracle_id: miracleId("healing-of-monica-besra"),
      url: "https://www.ewtnnews.com/world/europe/i-was-sure-that-it-was-mother-teresa-who-healed-me",
      title: "'I was sure that it was Mother Teresa who healed me' - EWTN News",
      source_type: "news_article",
    },
    // Padre Pio - M2
    {
      miracle_id: miracleId("healing-of-matteo-pio-colella"),
      url: "https://www.ewtnnews.com/world/europe/young-man-healed-by-padre-pio-recounts-story-of-miraculous-cure",
      title: "Young man healed by Padre Pio recounts story of miraculous cure - EWTN News",
      source_type: "news_article",
    },
    // Faustina Kowalska - M1
    {
      miracle_id: miracleId("healing-of-maureen-digan"),
      url: "https://www.ncregister.com/blog/divine-mercy-and-the-digans",
      title: "The Miraculous Cure That Got Sister Faustina Beatified - National Catholic Register",
      source_type: "news_article",
    },
    // Kateri Tekakwitha - M2
    {
      miracle_id: miracleId("healing-of-jake-finkbonner"),
      url: "https://www.ncregister.com/news/pope-approves-miracle-of-kateri-tekakwitha",
      title: "Pope Approves Miracle of Kateri Tekakwitha - National Catholic Register",
      source_type: "news_article",
    },
    // Andre Bessette - M2
    {
      miracle_id: miracleId("healing-of-child-traumatic-brain-injury"),
      url: "https://www.catholicnewsagency.com/search?q=Andre+Bessette+canonization+miracle",
      title: "CNA articles on Andre Bessette canonization miracle",
      source_type: "news_article",
    },
    // Carlo Acutis - M2
    {
      miracle_id: miracleId("healing-of-valeria-valverde"),
      url: "https://www.ewtnnews.com/vatican/carlo-acutis-to-be-first-millennial-saint-pope-francis-recognizes-miracle-for-canonization",
      title: "Carlo Acutis to be first millennial saint: Pope Francis recognizes miracle for canonization - EWTN News",
      source_type: "news_article",
    },
  ]);

  console.log("Seeding saint sources...");

  await db.insert(schema.saintSources).values([
    // John Paul II
    {
      saint_id: saintId("john-paul-ii"),
      url: "https://www.vatican.va/content/francesco/en/homilies/2014/documents/papa-francesco_20140427_omelia-canonizzazioni.html",
      title: "Holy Mass and Canonization of Blesseds John XXIII and John Paul II - Homily of Pope Francis",
      source_type: "vatican_decree",
    },
    // Mother Teresa
    {
      saint_id: saintId("mother-teresa"),
      url: "https://www.vatican.va/content/francesco/en/homilies/2016/documents/papa-francesco_20160904_omelia-canonizzazione-madre-teresa.html",
      title: "Holy Mass and Canonization of Mother Teresa of Calcutta - Homily of Pope Francis",
      source_type: "vatican_decree",
    },
    // Padre Pio
    {
      saint_id: saintId("padre-pio"),
      url: "https://www.vatican.va/content/john-paul-ii/en/homilies/2002/documents/hf_jp-ii_hom_20020616_padre-pio.html",
      title: "Canonization of Padre Pio of Pietrelcina - Homily of Pope John Paul II",
      source_type: "vatican_decree",
    },
    {
      saint_id: saintId("padre-pio"),
      url: "https://www.santuariopadrepio.it/",
      title: "Padre Pio Shrine, San Giovanni Rotondo - Official Site",
      source_type: "other",
    },
    // Faustina Kowalska
    {
      saint_id: saintId("faustina-kowalska"),
      url: "https://www.vatican.va/news_services/liturgy/saints/ns_lit_doc_20000430_faustina_en.html",
      title: "Canonization of St. Faustina Kowalska - Vatican Liturgy Page",
      source_type: "vatican_decree",
    },
    {
      saint_id: saintId("faustina-kowalska"),
      url: "https://www.faustyna.pl/",
      title: "Divine Mercy Sanctuary, Krakow-Lagiewniki - Official Site",
      source_type: "other",
    },
    // Gianna Beretta Molla
    {
      saint_id: saintId("gianna-beretta-molla"),
      url: "https://www.vatican.va/news_services/liturgy/saints/ns_lit_doc_20040516_beretta-molla_en.html",
      title: "Canonization of St. Gianna Beretta Molla - Vatican Liturgy Page",
      source_type: "vatican_decree",
    },
    {
      saint_id: saintId("gianna-beretta-molla"),
      url: "https://www.vatican.va/content/john-paul-ii/en/homilies/2004/documents/hf_jp-ii_hom_20040516_canonizations.html",
      title: "Canonization of Gianna Beretta Molla - Homily of Pope John Paul II",
      source_type: "vatican_decree",
    },
    {
      saint_id: saintId("gianna-beretta-molla"),
      url: "https://en.wikipedia.org/wiki/Gianna_Beretta_Molla",
      title: "Gianna Beretta Molla - Wikipedia",
      source_type: "academic",
    },
    // Kateri Tekakwitha
    {
      saint_id: saintId("kateri-tekakwitha"),
      url: "https://www.vatican.va/content/benedict-xvi/en/homilies/2012/documents/hf_ben-xvi_hom_20121021_canonizzazioni.html",
      title: "Canonization of Kateri Tekakwitha and others - Homily of Pope Benedict XVI",
      source_type: "vatican_decree",
    },
    {
      saint_id: saintId("kateri-tekakwitha"),
      url: "https://www.katerishrine.com/",
      title: "National Shrine of St. Kateri Tekakwitha, Fonda, NY",
      source_type: "other",
    },
    // Andre Bessette
    {
      saint_id: saintId("andre-bessette"),
      url: "https://www.vatican.va/content/benedict-xvi/en/homilies/2010/documents/hf_ben-xvi_hom_20101017_canonizations.html",
      title: "Canonization of Andre Bessette and others - Homily of Pope Benedict XVI",
      source_type: "vatican_decree",
    },
    {
      saint_id: saintId("andre-bessette"),
      url: "https://www.saint-joseph.org/",
      title: "St. Joseph's Oratory of Mount Royal - Official Site",
      source_type: "other",
    },
    {
      saint_id: saintId("andre-bessette"),
      url: "https://en.wikipedia.org/wiki/Andre_Bessette",
      title: "Andre Bessette - Wikipedia",
      source_type: "academic",
    },
    // Maximilian Kolbe
    {
      saint_id: saintId("maximilian-kolbe"),
      url: "https://www.vatican.va/news_services/liturgy/saints/ns_lit_doc_19821010_massimiliano_kolbe_it.html",
      title: "Canonization of St. Maximilian Kolbe - Vatican Liturgy Page (Italian)",
      source_type: "vatican_decree",
    },
    {
      saint_id: saintId("maximilian-kolbe"),
      url: "https://en.wikipedia.org/wiki/Maximilian_Kolbe",
      title: "Maximilian Kolbe - Wikipedia",
      source_type: "academic",
    },
    // Louis Martin
    {
      saint_id: saintId("louis-martin"),
      url: "https://www.vatican.va/content/francesco/en/homilies/2015/documents/papa-francesco_20151018_omelia-canonizzazioni.html",
      title: "Canonization of Louis and Zelie Martin and others - Homily of Pope Francis",
      source_type: "vatican_decree",
    },
    {
      saint_id: saintId("louis-martin"),
      url: "https://www.thereseoflisieux.org/",
      title: "Sanctuary of St. Therese and the Martin Family, Lisieux - Official Site",
      source_type: "other",
    },
    {
      saint_id: saintId("louis-martin"),
      url: "https://en.wikipedia.org/wiki/Louis_Martin_and_Marie-Azelie_Guerin",
      title: "Louis Martin and Marie-Azelie Guerin - Wikipedia",
      source_type: "academic",
    },
    // Zelie Martin
    {
      saint_id: saintId("zelie-martin"),
      url: "https://www.vatican.va/content/francesco/en/homilies/2015/documents/papa-francesco_20151018_omelia-canonizzazioni.html",
      title: "Canonization of Louis and Zelie Martin and others - Homily of Pope Francis",
      source_type: "vatican_decree",
    },
    {
      saint_id: saintId("zelie-martin"),
      url: "https://www.thereseoflisieux.org/",
      title: "Sanctuary of St. Therese and the Martin Family, Lisieux - Official Site",
      source_type: "other",
    },
    {
      saint_id: saintId("zelie-martin"),
      url: "https://en.wikipedia.org/wiki/Louis_Martin_and_Marie-Azelie_Guerin",
      title: "Louis Martin and Marie-Azelie Guerin - Wikipedia",
      source_type: "academic",
    },
    // Carlo Acutis
    {
      saint_id: saintId("carlo-acutis"),
      url: "https://www.carloacutis.com/",
      title: "Associazione Amici di Carlo Acutis - Official Site",
      source_type: "other",
    },
    // Juan Diego
    {
      saint_id: saintId("juan-diego"),
      url: "https://www.vatican.va/news_services/liturgy/saints/ns_lit_doc_20020731_juan-diego_en.html",
      title: "Canonization of St. Juan Diego - Vatican Liturgy Page",
      source_type: "vatican_decree",
    },
    {
      saint_id: saintId("juan-diego"),
      url: "https://en.wikipedia.org/wiki/Juan_Diego",
      title: "Juan Diego - Wikipedia",
      source_type: "academic",
    },
    {
      saint_id: saintId("juan-diego"),
      url: "https://virgendeguadalupe.mx/",
      title: "Basilica of Our Lady of Guadalupe - Official Site",
      source_type: "other",
    },
  ]);

  console.log("Seeding saint locations...");

  await db.insert(schema.saintLocations).values([
    // John Paul II
    { saint_id: saintId("john-paul-ii"), location_name: "Wadowice, Poland", lat: "49.883333", lng: "19.483333", location_type: "birthplace" },
    { saint_id: saintId("john-paul-ii"), location_name: "Vatican City (St. Peter's Basilica)", lat: "41.902200", lng: "12.453400", location_type: "tomb" },
    { saint_id: saintId("john-paul-ii"), location_name: "Vatican City", lat: "41.902200", lng: "12.453400", location_type: "death_place" },
    { saint_id: saintId("john-paul-ii"), location_name: "Sanctuary of St. John Paul II, Krakow, Poland", lat: "50.005200", lng: "19.974200", location_type: "shrine" },
    { saint_id: saintId("john-paul-ii"), location_name: "Divine Mercy Sanctuary, Krakow, Poland (relic)", lat: "50.054700", lng: "19.935100", location_type: "relic" },

    // Mother Teresa
    { saint_id: saintId("mother-teresa"), location_name: "Skopje, North Macedonia", lat: "42.000000", lng: "21.433333", location_type: "birthplace" },
    { saint_id: saintId("mother-teresa"), location_name: "Mother House of the Missionaries of Charity, Kolkata, India", lat: "22.544800", lng: "88.354200", location_type: "tomb" },
    { saint_id: saintId("mother-teresa"), location_name: "Mother House of the Missionaries of Charity, Kolkata, India", lat: "22.544800", lng: "88.354200", location_type: "death_place" },
    { saint_id: saintId("mother-teresa"), location_name: "Basilica of the Sacred Heart, Kolkata, India", lat: "22.544800", lng: "88.354200", location_type: "shrine" },

    // Padre Pio
    { saint_id: saintId("padre-pio"), location_name: "Pietrelcina, Benevento, Italy", lat: "41.200000", lng: "14.850000", location_type: "birthplace" },
    { saint_id: saintId("padre-pio"), location_name: "San Giovanni Rotondo, Foggia, Italy", lat: "41.705800", lng: "15.727800", location_type: "tomb" },
    { saint_id: saintId("padre-pio"), location_name: "San Giovanni Rotondo, Foggia, Italy", lat: "41.705800", lng: "15.727800", location_type: "death_place" },
    { saint_id: saintId("padre-pio"), location_name: "Our Lady of Grace Capuchin Church, San Giovanni Rotondo", lat: "41.705800", lng: "15.727800", location_type: "shrine" },

    // Faustina Kowalska
    { saint_id: saintId("faustina-kowalska"), location_name: "Glogowiec, Poland", lat: "52.050000", lng: "18.900000", location_type: "birthplace" },
    { saint_id: saintId("faustina-kowalska"), location_name: "Divine Mercy Sanctuary, Krakow-Lagiewniki, Poland", lat: "50.054700", lng: "19.935100", location_type: "tomb" },
    { saint_id: saintId("faustina-kowalska"), location_name: "Krakow, Poland", lat: "50.054700", lng: "19.935100", location_type: "death_place" },
    { saint_id: saintId("faustina-kowalska"), location_name: "Divine Mercy Sanctuary, Krakow-Lagiewniki, Poland", lat: "50.054700", lng: "19.935100", location_type: "shrine" },

    // Gianna Beretta Molla
    { saint_id: saintId("gianna-beretta-molla"), location_name: "Magenta, Milan, Italy", lat: "45.466667", lng: "8.883333", location_type: "birthplace" },
    { saint_id: saintId("gianna-beretta-molla"), location_name: "Monza, Italy", lat: "45.583333", lng: "9.266667", location_type: "death_place" },
    { saint_id: saintId("gianna-beretta-molla"), location_name: "Mesero Cemetery, Mesero, Italy", lat: "45.500000", lng: "8.850000", location_type: "tomb" },
    { saint_id: saintId("gianna-beretta-molla"), location_name: "Sanctuary of Santa Maria Nascente, Ponte Lambro, Italy", lat: "45.833333", lng: "9.216667", location_type: "shrine" },

    // Kateri Tekakwitha
    { saint_id: saintId("kateri-tekakwitha"), location_name: "Ossernenon (Auriesville, New York, USA)", lat: "42.983333", lng: "-74.316667", location_type: "birthplace" },
    { saint_id: saintId("kateri-tekakwitha"), location_name: "Kahnawake, Quebec, Canada", lat: "45.416667", lng: "-73.583333", location_type: "death_place" },
    { saint_id: saintId("kateri-tekakwitha"), location_name: "St. Francis Xavier Mission, Kahnawake, Quebec, Canada", lat: "45.416667", lng: "-73.583333", location_type: "tomb" },
    { saint_id: saintId("kateri-tekakwitha"), location_name: "St. Kateri National Shrine, Auriesville, New York, USA", lat: "42.983333", lng: "-74.316667", location_type: "shrine" },
    { saint_id: saintId("kateri-tekakwitha"), location_name: "St. Kateri Shrine, Fonda, New York, USA", lat: "42.950000", lng: "-74.383333", location_type: "shrine" },

    // Andre Bessette
    { saint_id: saintId("andre-bessette"), location_name: "Mont-Saint-Gregoire, Quebec, Canada", lat: "45.366667", lng: "-73.150000", location_type: "birthplace" },
    { saint_id: saintId("andre-bessette"), location_name: "St. Joseph's Oratory, Montreal, Quebec, Canada", lat: "45.491600", lng: "-73.622200", location_type: "tomb" },
    { saint_id: saintId("andre-bessette"), location_name: "St. Joseph's Oratory, Montreal, Quebec, Canada", lat: "45.491600", lng: "-73.622200", location_type: "death_place" },
    { saint_id: saintId("andre-bessette"), location_name: "St. Joseph's Oratory, Montreal, Quebec, Canada", lat: "45.491600", lng: "-73.622200", location_type: "shrine" },

    // Maximilian Kolbe
    { saint_id: saintId("maximilian-kolbe"), location_name: "Zdunska Wola, Poland", lat: "51.600000", lng: "18.933333", location_type: "birthplace" },
    { saint_id: saintId("maximilian-kolbe"), location_name: "Auschwitz-Birkenau, Poland", lat: "50.033333", lng: "19.183333", location_type: "death_place" },
    { saint_id: saintId("maximilian-kolbe"), location_name: "Basilica of St. Maximilian Kolbe, Niepokalanow, Poland", lat: "52.233333", lng: "20.316667", location_type: "tomb" },
    { saint_id: saintId("maximilian-kolbe"), location_name: "Auschwitz-Birkenau, Poland", lat: "50.033333", lng: "19.183333", location_type: "shrine" },
    { saint_id: saintId("maximilian-kolbe"), location_name: "Niepokalanow Monastery, Poland", lat: "52.233333", lng: "20.316667", location_type: "shrine" },

    // Louis Martin
    { saint_id: saintId("louis-martin"), location_name: "Bordeaux, France", lat: "44.833333", lng: "-0.566667", location_type: "birthplace" },
    { saint_id: saintId("louis-martin"), location_name: "Alencon, France", lat: "48.433333", lng: "0.083333", location_type: "death_place" },
    { saint_id: saintId("louis-martin"), location_name: "Basilica of St. Therese, Lisieux, France", lat: "49.050000", lng: "0.233333", location_type: "tomb" },
    { saint_id: saintId("louis-martin"), location_name: "Alencon, France (family home)", lat: "48.433333", lng: "0.083333", location_type: "shrine" },

    // Zelie Martin
    { saint_id: saintId("zelie-martin"), location_name: "Gandelain, France", lat: "48.483333", lng: "-0.033333", location_type: "birthplace" },
    { saint_id: saintId("zelie-martin"), location_name: "Alencon, France", lat: "48.433333", lng: "0.083333", location_type: "death_place" },
    { saint_id: saintId("zelie-martin"), location_name: "Basilica of St. Therese, Lisieux, France", lat: "49.050000", lng: "0.233333", location_type: "tomb" },
    { saint_id: saintId("zelie-martin"), location_name: "Alencon, France (family home)", lat: "48.433333", lng: "0.083333", location_type: "shrine" },

    // Carlo Acutis
    { saint_id: saintId("carlo-acutis"), location_name: "London, England", lat: "51.507400", lng: "-0.127800", location_type: "birthplace" },
    { saint_id: saintId("carlo-acutis"), location_name: "Monza, Italy", lat: "45.583333", lng: "9.266667", location_type: "death_place" },
    { saint_id: saintId("carlo-acutis"), location_name: "Sanctuary of the Spoliation, Assisi, Italy", lat: "43.066667", lng: "12.616667", location_type: "tomb" },
    { saint_id: saintId("carlo-acutis"), location_name: "Assisi, Italy", lat: "43.066667", lng: "12.616667", location_type: "shrine" },
    { saint_id: saintId("carlo-acutis"), location_name: "Santa Maria Maggiore, Rome, Italy (first-class relic)", lat: "41.897500", lng: "12.498900", location_type: "relic" },

    // Juan Diego
    { saint_id: saintId("juan-diego"), location_name: "Cuauhtitlan, Mexico", lat: "19.683333", lng: "-99.183333", location_type: "birthplace" },
    { saint_id: saintId("juan-diego"), location_name: "Tepeyac Hill, Mexico City, Mexico", lat: "19.484400", lng: "-99.117500", location_type: "death_place" },
    { saint_id: saintId("juan-diego"), location_name: "Basilica of Our Lady of Guadalupe, Mexico City", lat: "19.484400", lng: "-99.117500", location_type: "tomb" },
    { saint_id: saintId("juan-diego"), location_name: "Basilica of Our Lady of Guadalupe, Mexico City", lat: "19.484400", lng: "-99.117500", location_type: "shrine" },
  ]);

  console.log("Seeding complete.");
  console.log(`  Saints: ${insertedSaints.length}`);
  console.log("  Saint relations: 2");
  console.log(`  Miracles: ${insertedMiracles.length}`);
  console.log("  Miracle sources: 8");
  console.log("  Saint sources: 26");
  console.log("  Saint locations: 50");
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
