import "dotenv/config";
import { createDb } from "./index";
import * as schema from "./schema";

const db = createDb(process.env.DATABASE_URL!);

const LOREM_BIO =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.";

const LOREM_SYNOPSIS =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet consectetur adipisci velit.";

async function seed() {
  console.log("Seeding saints...");

  const insertedSaints = await db
    .insert(schema.saints)
    .values([
      {
        slug: "john-paul-ii",
        name: "John Paul II",
        birth_name: "Karol Jozef Wojtyla",
        birth_date: "1920-05-18",
        death_date: "2005-04-02",
        feast_day: "October 22",
        nationality: "Polish",
        birth_place: "Wadowice, Poland",
        death_place: "Vatican City",
        beatification_date: "2011-05-01",
        beatified_by: "Pope Benedict XVI",
        canonization_date: "2014-04-27",
        canonized_by: "Pope Francis",
        canonization_type: "confessor",
        canonization_stage: "saint",
        patronage: ["World Youth Day", "families", "young Catholics"],
        noted_for: [
          "Theology of the Body",
          "interfaith dialogue",
          "the Great Jubilee",
          "World Youth Day",
          "Parkinson's witness",
          "pro-life witness",
          "Polish solidarity",
        ],
        biography_short: LOREM_BIO,
        total_attributed_miracles: 2,
        image_url: "https://commons.wikimedia.org/wiki/File:JPII_29_09_2004_2.JPG",
        wikipedia_url: "https://en.wikipedia.org/wiki/Pope_John_Paul_II",
      },
      {
        slug: "mother-teresa",
        name: "Mother Teresa",
        birth_name: "Anjeze Gonxhe Bojaxhiu",
        birth_date: "1910-08-26",
        death_date: "1997-09-05",
        feast_day: "September 5",
        religious_order: "Missionaries of Charity",
        nationality: "Albanian",
        birth_place: "Skopje (now North Macedonia)",
        death_place: "Kolkata, India",
        beatification_date: "2003-10-19",
        beatified_by: "Pope John Paul II",
        canonization_date: "2016-09-04",
        canonized_by: "Pope Francis",
        canonization_type: "confessor",
        canonization_stage: "saint",
        patronage: ["Missionaries of Charity", "poor and sick"],
        noted_for: [
          "serving the poorest of the poor",
          "Calcutta",
          "homes for the dying",
          "leper colonies",
          "missionary work in India",
          "Nobel Peace Prize",
        ],
        biography_short: LOREM_BIO,
        total_attributed_miracles: 2,
        image_url: "https://commons.wikimedia.org/wiki/File:MotherTeresa_090.jpg",
        wikipedia_url: "https://en.wikipedia.org/wiki/Mother_Teresa",
      },
      {
        slug: "padre-pio",
        name: "Padre Pio",
        birth_name: "Francesco Forgione",
        birth_date: "1887-05-25",
        death_date: "1968-09-23",
        feast_day: "September 23",
        religious_order: "Capuchin Franciscan",
        nationality: "Italian",
        birth_place: "Pietrelcina, Italy",
        death_place: "San Giovanni Rotondo, Italy",
        beatification_date: "1999-05-02",
        beatified_by: "Pope John Paul II",
        canonization_date: "2002-06-16",
        canonized_by: "Pope John Paul II",
        canonization_type: "confessor",
        canonization_stage: "saint",
        patronage: ["stress relief", "civil defense volunteers", "adolescents"],
        noted_for: [
          "stigmata",
          "bilocation",
          "spiritual direction",
          "confession",
          "healing during lifetime",
          "incorrupt body",
          "San Giovanni Rotondo",
          "suffering",
        ],
        biography_short: LOREM_BIO,
        total_attributed_miracles: 2,
        image_url: "https://commons.wikimedia.org/wiki/File:Padre_Pio_portrait.jpg",
        wikipedia_url: "https://en.wikipedia.org/wiki/Padre_Pio",
      },
      {
        slug: "faustina-kowalska",
        name: "Faustina Kowalska",
        birth_name: "Helena Kowalska",
        birth_date: "1905-08-25",
        death_date: "1938-10-05",
        feast_day: "October 5",
        religious_order: "Congregation of the Sisters of Our Lady of Mercy",
        nationality: "Polish",
        birth_place: "Glogowiec, Poland",
        death_place: "Krakow, Poland",
        beatification_date: "1993-04-18",
        beatified_by: "Pope John Paul II",
        canonization_date: "2000-04-30",
        canonized_by: "Pope John Paul II",
        canonization_type: "virgin",
        canonization_stage: "saint",
        patronage: ["Divine Mercy devotion", "sinners", "World Youth Day"],
        noted_for: [
          "Divine Mercy revelations",
          "the Divine Mercy image",
          "Chaplet of Divine Mercy",
          "Feast of Mercy",
          "mystical visions",
          "mercy",
        ],
        biography_short: LOREM_BIO,
        total_attributed_miracles: 2,
        image_url:
          "https://commons.wikimedia.org/wiki/File:Saint_Faustyna_Kowalska_portrait_(1931).jpg",
        wikipedia_url: "https://en.wikipedia.org/wiki/Faustina_Kowalska",
      },
      {
        slug: "gianna-beretta-molla",
        name: "Gianna Beretta Molla",
        birth_name: "Gianna Beretta Molla",
        birth_date: "1922-10-04",
        death_date: "1962-04-28",
        feast_day: "April 28",
        nationality: "Italian",
        birth_place: "Magenta, Italy",
        death_place: "Monza, Italy",
        beatification_date: "1994-04-24",
        beatified_by: "Pope John Paul II",
        canonization_date: "2004-05-16",
        canonized_by: "Pope John Paul II",
        canonization_type: "married_couple",
        canonization_stage: "saint",
        patronage: ["mothers", "families", "physicians", "unborn children"],
        noted_for: [
          "pro-life witness",
          "choosing unborn child over own life",
          "sanctity of life",
          "breast cancer",
          "pregnancy",
          "motherhood",
          "physicians",
        ],
        biography_short: LOREM_BIO,
        total_attributed_miracles: 2,
        image_url: "https://commons.wikimedia.org/wiki/File:GiannaBerettaMolla.jpg",
        wikipedia_url: "https://en.wikipedia.org/wiki/Gianna_Beretta_Molla",
      },
      {
        slug: "kateri-tekakwitha",
        name: "Kateri Tekakwitha",
        birth_name: "Kateri Tekakwitha",
        birth_date: "1656-01-01",
        death_date: "1680-04-17",
        feast_day: "July 14",
        nationality: "Mohawk / Native American",
        birth_place: "Ossernenon (now Auriesville, New York)",
        death_place: "Kahnawake, Quebec, Canada",
        beatification_date: "1980-06-22",
        beatified_by: "Pope John Paul II",
        canonization_date: "2012-10-21",
        canonized_by: "Pope Benedict XVI",
        canonization_type: "virgin",
        canonization_stage: "saint",
        patronage: ["Native Americans", "ecology", "environmentalists", "exiles"],
        noted_for: [
          "Lily of the Mohawks",
          "smallpox survivor",
          "convert",
          "virgin",
          "nature",
          "indigenous Catholicism",
          "Native American spirituality",
        ],
        biography_short: LOREM_BIO,
        total_attributed_miracles: 2,
        image_url: "https://commons.wikimedia.org/wiki/File:Kateri_Tekakwitha_1690.jpg",
        wikipedia_url: "https://en.wikipedia.org/wiki/Kateri_Tekakwitha",
      },
      {
        slug: "andre-bessette",
        name: "Andre Bessette",
        birth_name: "Andre Bessette",
        birth_date: "1845-08-09",
        death_date: "1937-01-06",
        feast_day: "January 6",
        religious_order: "Congregation of Holy Cross",
        nationality: "Canadian",
        birth_place: "Mont-Saint-Gregoire, Quebec, Canada",
        death_place: "Montreal, Quebec, Canada",
        beatification_date: "1982-05-23",
        beatified_by: "Pope John Paul II",
        canonization_date: "2010-10-17",
        canonized_by: "Pope Benedict XVI",
        canonization_type: "confessor",
        canonization_stage: "saint",
        patronage: ["the sick", "the grieving", "family caregivers"],
        noted_for: [
          "St. Joseph's Oratory",
          "healing the sick",
          "St. Joseph devotion",
          "porter/humble service",
          "Montreal",
          "thousands of healings",
        ],
        biography_short: LOREM_BIO,
        total_attributed_miracles: 2,
        image_url: "https://commons.wikimedia.org/wiki/File:Frere_Andre_1920.jpg",
        wikipedia_url: "https://en.wikipedia.org/wiki/Andre_Bessette",
      },
      {
        slug: "maximilian-kolbe",
        name: "Maximilian Kolbe",
        birth_name: "Rajmund Kolbe",
        birth_date: "1894-01-08",
        death_date: "1941-08-14",
        feast_day: "August 14",
        religious_order: "Conventual Franciscan",
        nationality: "Polish",
        birth_place: "Zdunska Wola, Poland",
        death_place: "Auschwitz, Poland",
        beatification_date: "1971-10-17",
        beatified_by: "Pope Paul VI",
        canonization_date: "1982-10-10",
        canonized_by: "Pope John Paul II",
        canonization_type: "martyr",
        canonization_stage: "saint",
        patronage: ["addicts", "journalists", "prisoners", "families", "pro-life movement"],
        noted_for: [
          "martyr of charity",
          "Auschwitz",
          "volunteered to die for another prisoner",
          "Immaculata devotion",
          "Franciscan",
          "Knights of the Immaculata",
        ],
        biography_short: LOREM_BIO,
        total_attributed_miracles: 2,
        image_url: "https://commons.wikimedia.org/wiki/File:Fr.Maximilian_Kolbe_1939.jpg",
        wikipedia_url: "https://en.wikipedia.org/wiki/Maximilian_Kolbe",
      },
      {
        slug: "louis-martin",
        name: "Louis Martin",
        birth_name: "Louis Martin",
        birth_date: "1823-08-22",
        death_date: "1894-07-29",
        feast_day: "July 12",
        nationality: "French",
        birth_place: "Bordeaux, France",
        death_place: "France",
        beatification_date: "2008-10-19",
        beatified_by: "Pope Benedict XVI",
        canonization_date: "2015-10-18",
        canonized_by: "Pope Francis",
        canonization_type: "married_couple",
        canonization_stage: "saint",
        patronage: ["married couples", "families", "parents", "Catholic families"],
        noted_for: [
          "first married couple canonized together",
          "parenting St. Therese of Lisieux",
          "ordinary family holiness",
          "small business owners",
          "marriage",
        ],
        biography_short: LOREM_BIO,
        total_attributed_miracles: 1,
        image_url: "https://commons.wikimedia.org/wiki/File:Louis_Martin_1.jpg",
        wikipedia_url: "https://en.wikipedia.org/wiki/Louis_and_Zelie_Martin",
      },
      {
        slug: "zelie-martin",
        name: "Zélie Martin",
        birth_name: "Zelie Guerin Martin",
        birth_date: "1831-12-23",
        death_date: "1877-08-28",
        feast_day: "July 12",
        nationality: "French",
        birth_place: "Gandelain, France",
        death_place: "France",
        beatification_date: "2008-10-19",
        beatified_by: "Pope Benedict XVI",
        canonization_date: "2015-10-18",
        canonized_by: "Pope Francis",
        canonization_type: "married_couple",
        canonization_stage: "saint",
        patronage: ["married couples", "families", "parents", "Catholic families"],
        noted_for: [
          "first married couple canonized together",
          "parenting St. Therese of Lisieux",
          "ordinary family holiness",
          "lace maker",
          "marriage",
        ],
        biography_short: LOREM_BIO,
        total_attributed_miracles: 1,
        image_url: "https://commons.wikimedia.org/wiki/File:Louis_Martin_1.jpg",
        wikipedia_url: "https://en.wikipedia.org/wiki/Louis_and_Zelie_Martin",
      },
      {
        slug: "carlo-acutis",
        name: "Carlo Acutis",
        birth_name: "Carlo Acutis",
        birth_date: "1991-05-03",
        death_date: "2006-10-12",
        feast_day: "October 12",
        nationality: "Italian",
        birth_place: "London, England (raised in Milan, Italy)",
        death_place: "Monza, Italy",
        beatification_date: "2020-10-10",
        beatified_by: "Cardinal Agostino Vallini (Assisi)",
        canonization_date: "2025-09-07",
        canonized_by: "Pope Leo XIV",
        canonization_type: "confessor",
        canonization_stage: "saint",
        patronage: ["computer programmers", "internet users", "youth", "Eucharistic devotion"],
        noted_for: [
          "technology",
          "computer programming",
          "Eucharistic miracles website",
          "teenage holiness",
          "gaming",
          "youth evangelization",
        ],
        biography_short: LOREM_BIO,
        total_attributed_miracles: 2,
        wikipedia_url: "https://en.wikipedia.org/wiki/Carlo_Acutis",
      },
      {
        slug: "juan-diego",
        name: "Juan Diego",
        birth_name: "Juan Diego Cuauhtlatoatzin",
        birth_date: "1474-01-01",
        death_date: "1548-01-01",
        feast_day: "December 9",
        nationality: "Aztec / Indigenous Mexican",
        birth_place: "Cuauhtitlan, Aztec Empire (modern Mexico)",
        death_place: "Tepeyac, Mexico City",
        beatification_date: "1990-05-06",
        beatified_by: "Pope John Paul II (equipollent)",
        canonization_date: "2002-07-31",
        canonized_by: "Pope John Paul II",
        canonization_type: "confessor",
        canonization_stage: "saint",
        patronage: ["indigenous peoples of the Americas"],
        noted_for: [
          "Our Lady of Guadalupe apparition",
          "the Tilma",
          "indigenous convert",
          "simple faith",
          "messenger",
          "marian",
        ],
        biography_short: LOREM_BIO,
        total_attributed_miracles: 2,
        image_url: "https://commons.wikimedia.org/wiki/File:Juan-Diego.jpg",
        wikipedia_url: "https://en.wikipedia.org/wiki/Juan_Diego",
      },
    ])
    .returning({ id: schema.saints.id, slug: schema.saints.slug });

  console.log(`Inserted ${insertedSaints.length} saints.`);

  const saintId = (slug: string) => {
    const s = insertedSaints.find((r) => r.slug === slug);
    if (!s) throw new Error(`Saint not found: ${slug}`);
    return s.id;
  };

  console.log("Seeding saint relations...");

  await db.insert(schema.saintRelations).values([
    {
      saint_id: saintId("louis-martin"),
      related_saint_id: saintId("zelie-martin"),
      relation_type: "canonized_together",
    },
    {
      saint_id: saintId("zelie-martin"),
      related_saint_id: saintId("louis-martin"),
      relation_type: "canonized_together",
    },
  ]);

  console.log("Seeding miracles...");

  await db.insert(schema.miracles).values([
    // ── John Paul II ──────────────────────────────────────────────────────────
    {
      saint_id: saintId("john-paul-ii"),
      slug: "healing-of-sr-marie-simon-pierre",
      title: "Healing of Sr. Marie Simon-Pierre",
      miracle_category: "intercessory",
      type: "healing",
      topics: ["neurological", "elderly", "perseverance", "pro-life", "hope"],
      date_of_event: "2005-06-02",
      date_precision: "exact_day",
      timing_relative_to_saint_death: "posthumous",
      location_name: "Aix-en-Provence, France",
      country: "France",
      recipient_name: "Sr. Marie Simon-Pierre",
      recipient_privacy: "public",
      recipient_gender: "female",
      medical_diagnosis: "Parkinson's disease (diagnosed 2001)",
      cure_details:
        "Severe Parkinson's — could not write or drive. On the night of June 2, she felt compelled to write JPII's name and found her hand steady. Complete recovery.",
      cure_characteristics: "instant_complete",
      was_medically_verified: true,
      medical_verification_date: "2009-01-01",
      intercessory_medium: "prayer_only",
      vatican_recognized: true,
      vatican_medical_board_verdict: "Declared medically inexplicable in 2009",
      used_for_beatification: true,
      used_for_canonization: false,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },
    {
      saint_id: saintId("john-paul-ii"),
      slug: "healing-of-floribeth-mora-diaz",
      title: "Healing of Floribeth Mora Diaz",
      miracle_category: "intercessory",
      type: "healing",
      topics: ["neurological", "mothers", "hope"],
      date_of_event: "2011-05-01",
      date_precision: "exact_day",
      timing_relative_to_saint_death: "posthumous",
      location_name: "Costa Rica (home)",
      country: "Costa Rica",
      recipient_name: "Floribeth Mora Diaz",
      recipient_privacy: "public",
      recipient_gender: "female",
      medical_diagnosis: "Severe brain aneurysm (diagnosed April 2011, terminal, sent home to die)",
      cure_details:
        "While watching JPII's beatification on TV, she heard his voice say \"Don't be afraid. I am with you.\" She felt immediate improvement.",
      cure_characteristics: "instant_complete",
      was_medically_verified: true,
      medical_verification_date: "2013-01-01",
      intercessory_medium: "prayer_only",
      vatican_recognized: true,
      vatican_medical_board_verdict: "Declared medically inexplicable in 2013",
      used_for_beatification: false,
      used_for_canonization: true,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },

    // ── Mother Teresa ─────────────────────────────────────────────────────────
    {
      saint_id: saintId("mother-teresa"),
      slug: "healing-of-monica-besra",
      title: "Healing of Monica Besra",
      miracle_category: "intercessory",
      type: "healing",
      topics: ["cancer", "mothers", "financial-hardship", "hope"],
      date_of_event: "1998-09-05",
      date_precision: "exact_day",
      timing_relative_to_saint_death: "posthumous",
      location_name: "Nadia district, West Bengal",
      country: "India",
      region: "West Bengal",
      recipient_name: "Monica Besra",
      recipient_privacy: "public",
      recipient_gender: "female",
      medical_diagnosis: "Large benign abdominal/ovarian tumor",
      cure_details:
        "After applying a medallion of Mother Teresa and praying, she felt intense warmth and the tumor disappeared.",
      cure_characteristics: "instant_complete",
      was_medically_verified: true,
      medical_verification_date: "2002-01-01",
      intercessory_medium: "medallion",
      vatican_recognized: true,
      vatican_medical_board_verdict: "Declared medically inexplicable in 2002",
      used_for_beatification: true,
      used_for_canonization: false,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },
    {
      saint_id: saintId("mother-teresa"),
      slug: "healing-of-marcilio-haddad-andrino",
      title: "Healing of Marcilio Haddad Andrino",
      miracle_category: "intercessory",
      type: "healing",
      topics: ["neurological", "infectious", "hope"],
      date_of_event: "2008-12-09",
      date_precision: "exact_day",
      timing_relative_to_saint_death: "posthumous",
      location_name: "Santos",
      country: "Brazil",
      region: "Sao Paulo",
      recipient_name: "Marcilio Haddad Andrino",
      recipient_privacy: "public",
      recipient_gender: "male",
      medical_diagnosis: "Multiple brain abscesses / viral meningoencephalitis with hydrocephalus",
      cure_details:
        "In a coma, on life support, family told to prepare for his death. His wife prayed with a relic. Doctors found him conscious the next morning with all symptoms gone.",
      cure_characteristics: "instant_complete",
      was_medically_verified: true,
      medical_verification_date: "2015-01-01",
      intercessory_medium: "relic",
      vatican_recognized: true,
      vatican_medical_board_verdict: "Declared medically inexplicable in 2015",
      used_for_beatification: false,
      used_for_canonization: true,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },

    // ── Padre Pio ─────────────────────────────────────────────────────────────
    {
      saint_id: saintId("padre-pio"),
      slug: "healing-of-consiglia-de-martino",
      title: "Healing of Consiglia De Martino",
      miracle_category: "intercessory",
      type: "healing",
      topics: ["gastrointestinal", "infectious", "hope"],
      date_of_event: "1958-10-07",
      date_precision: "exact_day",
      timing_relative_to_saint_death: "during_lifetime",
      location_name: "Salerno, Italy",
      country: "Italy",
      recipient_name: "Consiglia De Martino",
      recipient_privacy: "public",
      recipient_gender: "female",
      medical_diagnosis: "Ruptured stomach / severe peritonitis from burst appendix",
      cure_details:
        "Near death after botched surgery. Father brought a photo of Padre Pio to her hospital room. She saw a vision of a Capuchin friar who said \"Don't you know I only work at night?\" Healed instantly.",
      cure_characteristics: "instant_complete",
      was_medically_verified: true,
      intercessory_medium: "saint_image",
      vatican_recognized: true,
      vatican_medical_board_verdict: "Declared medically inexplicable",
      used_for_beatification: true,
      used_for_canonization: false,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },
    {
      saint_id: saintId("padre-pio"),
      slug: "healing-of-matteo-pio-colella",
      title: "Healing of Matteo Pio Colella",
      miracle_category: "intercessory",
      type: "healing",
      topics: ["neurological", "infectious", "children", "hope"],
      date_of_event: "2000-07-21",
      date_precision: "exact_day",
      timing_relative_to_saint_death: "posthumous",
      location_name: "San Giovanni Rotondo, Italy",
      country: "Italy",
      recipient_name: "Matteo Pio Colella",
      recipient_privacy: "public",
      recipient_gender: "male",
      recipient_age_at_event: 7,
      medical_diagnosis: "Coma after meningitis, severe brain damage, multiple organ failure",
      cure_details:
        "The 7-year-old was dying. His mother prayed intensely at Padre Pio's tomb. He recovered fully with no brain damage.",
      cure_characteristics: "instant_complete",
      was_medically_verified: true,
      intercessory_medium: "tomb_prayer",
      vatican_recognized: true,
      vatican_medical_board_verdict: "Declared medically inexplicable",
      used_for_beatification: false,
      used_for_canonization: true,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },
    {
      saint_id: saintId("padre-pio"),
      slug: "stigmata-of-padre-pio",
      title: "The Stigmata of Padre Pio",
      miracle_category: "associated",
      type: "stigmata",
      topics: ["stigmata", "perseverance", "spiritual-direction", "saints-bodies"],
      date_of_event: "1918-09-20",
      date_precision: "exact_day",
      timing_relative_to_saint_death: "during_lifetime",
      location_name: "San Giovanni Rotondo, Italy",
      country: "Italy",
      recipient_privacy: "not_applicable",
      recipient_gender: "not_applicable",
      cure_details:
        "Received visible stigmata (wounds of Christ) on hands, feet, and side. Visible for 50 years until his death. Examined by multiple doctors, Vatican investigators, and photographers. Remained fresh and never became infected despite no treatment.",
      cure_characteristics: "not_applicable",
      was_medically_verified: true,
      intercessory_medium: "not_applicable",
      vatican_recognized: true,
      vatican_medical_board_verdict: "Vatican commission (1925) declared wounds not of natural origin",
      used_for_beatification: false,
      used_for_canonization: false,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },
    {
      saint_id: saintId("padre-pio"),
      slug: "bilocation-of-padre-pio",
      title: "Bilocation of Padre Pio",
      miracle_category: "associated",
      type: "bilocation",
      topics: ["bilocation"],
      date_precision: "century",
      timing_relative_to_saint_death: "during_lifetime",
      location_name: "Multiple locations worldwide",
      country: "Italy",
      recipient_privacy: "not_applicable",
      recipient_gender: "not_applicable",
      cure_details:
        "Numerous documented accounts of Padre Pio appearing in two places simultaneously. Often reported during WWII when soldiers saw him on battlefields, only to learn he was at the monastery in Italy. Also reported in confessionals, during Mass, and at bedsides of the dying.",
      cure_characteristics: "not_applicable",
      was_medically_verified: false,
      intercessory_medium: "not_applicable",
      vatican_recognized: true,
      used_for_beatification: false,
      used_for_canonization: false,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },

    // ── Faustina Kowalska ─────────────────────────────────────────────────────
    {
      saint_id: saintId("faustina-kowalska"),
      slug: "healing-of-maureen-digan",
      title: "Healing of Maureen Digan",
      miracle_category: "intercessory",
      type: "healing",
      topics: ["cardiovascular", "hope", "perseverance"],
      date_of_event: "1981-03-13",
      date_precision: "exact_day",
      timing_relative_to_saint_death: "posthumous",
      location_name: "Fall River, Massachusetts (healing at Krakow shrine)",
      country: "USA",
      region: "Massachusetts",
      recipient_name: "Maureen Digan",
      recipient_privacy: "public",
      recipient_gender: "female",
      medical_diagnosis: "Lymphedema (chronic, severe leg swelling, unable to walk for 36 years)",
      cure_details:
        "While visiting St. Faustina's tomb in Poland, prayed and felt a cracking sensation. Swelling drained immediately and she could walk.",
      cure_characteristics: "instant_complete",
      was_medically_verified: true,
      medical_verification_date: "1992-01-01",
      intercessory_medium: "tomb_prayer",
      vatican_recognized: true,
      vatican_medical_board_verdict: "Declared medically inexplicable in 1992",
      used_for_beatification: true,
      used_for_canonization: false,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },
    {
      saint_id: saintId("faustina-kowalska"),
      slug: "healing-of-fr-ronald-pytel",
      title: "Healing of Fr. Ronald Pytel",
      miracle_category: "intercessory",
      type: "healing",
      topics: ["cardiovascular", "conversion", "hope"],
      date_of_event: "1995-01-01",
      date_precision: "year",
      timing_relative_to_saint_death: "posthumous",
      location_name: "Baltimore, Maryland",
      country: "USA",
      region: "Maryland",
      recipient_name: "Fr. Ronald Pytel",
      recipient_privacy: "public",
      recipient_gender: "male",
      medical_diagnosis: "Advanced arteriosclerosis, severe angina (needed bypass surgery)",
      cure_details:
        "Told he needed bypass surgery. After praying to Faustina, symptoms disappeared and medical tests showed a normal heart.",
      cure_characteristics: "instant_complete",
      was_medically_verified: true,
      medical_verification_date: "1999-01-01",
      intercessory_medium: "prayer_only",
      vatican_recognized: true,
      vatican_medical_board_verdict: "Declared medically inexplicable in 1999",
      used_for_beatification: false,
      used_for_canonization: true,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },
    {
      saint_id: saintId("faustina-kowalska"),
      slug: "divine-mercy-revelations",
      title: "Divine Mercy Revelations to St. Faustina",
      miracle_category: "associated",
      type: "apparition",
      topics: ["conversion", "spiritual-direction"],
      date_of_event: "1931-01-01",
      date_precision: "decade",
      timing_relative_to_saint_death: "during_lifetime",
      location_name: "Krakow and Vilnius (convents)",
      country: "Poland",
      recipient_name: "St. Faustina Kowalska",
      recipient_privacy: "public",
      recipient_gender: "female",
      cure_details:
        "Multiple visions of Jesus Christ beginning February 22, 1931. Jesus appeared with rays of red and white light, instructing Faustina to have an image painted (\"Jesus, I trust in You\"). Dictated the Chaplet of Divine Mercy and established Divine Mercy Sunday. Faustina recorded everything in her Diary (600+ pages), later approved by the Vatican.",
      cure_characteristics: "not_applicable",
      was_medically_verified: false,
      intercessory_medium: "not_applicable",
      vatican_recognized: true,
      vatican_decree_date: "2000-01-01",
      used_for_beatification: false,
      used_for_canonization: false,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },

    // ── Gianna Beretta Molla ───────────────────────────────────────────────────
    {
      saint_id: saintId("gianna-beretta-molla"),
      slug: "healing-of-sr-maria-vergine-colombo",
      title: "Healing of Sr. Maria Vergine Colombo",
      miracle_category: "intercessory",
      type: "healing",
      topics: ["cancer", "mothers", "pro-life", "hope"],
      date_of_event: "1980-01-01",
      date_precision: "decade",
      timing_relative_to_saint_death: "posthumous",
      country: "Brazil",
      recipient_name: "Sr. Maria Vergine Colombo",
      recipient_privacy: "public",
      recipient_gender: "female",
      medical_diagnosis: "Malignant, metastasizing breast tumor",
      cure_details:
        "During surgery for mastectomy, tumor was found vanished. Only a biopsy scar remained.",
      cure_characteristics: "instant_complete",
      was_medically_verified: true,
      intercessory_medium: "prayer_only",
      vatican_recognized: true,
      vatican_medical_board_verdict: "Declared medically inexplicable",
      used_for_beatification: true,
      used_for_canonization: false,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },
    {
      saint_id: saintId("gianna-beretta-molla"),
      slug: "healing-of-elizabeth-comparini",
      title: "Healing of Elizabeth Comparini",
      miracle_category: "intercessory",
      type: "healing",
      topics: ["pregnancy-and-childbirth", "mothers", "children", "pro-life", "hope"],
      date_of_event: "2002-01-01",
      date_precision: "year",
      timing_relative_to_saint_death: "posthumous",
      country: "Brazil",
      recipient_name: "Elizabeth Comparini",
      recipient_privacy: "public",
      recipient_gender: "female",
      medical_diagnosis: "Severe placental abruption with hemorrhaging and fetal distress",
      cure_details:
        "Doctors told her both she and baby would die. She prayed to Gianna. Bleeding stopped, both survived healthy.",
      cure_characteristics: "instant_complete",
      was_medically_verified: true,
      intercessory_medium: "prayer_only",
      vatican_recognized: true,
      vatican_medical_board_verdict: "Declared medically inexplicable",
      used_for_beatification: false,
      used_for_canonization: true,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },

    // ── Kateri Tekakwitha ─────────────────────────────────────────────────────
    {
      saint_id: saintId("kateri-tekakwitha"),
      slug: "healing-of-native-american-boy",
      title: "Healing of an Unnamed Native American Boy",
      miracle_category: "intercessory",
      type: "healing",
      topics: ["children", "native-and-indigenous", "hope"],
      date_of_event: "1940-01-01",
      date_precision: "decade",
      timing_relative_to_saint_death: "posthumous",
      country: "USA",
      recipient_privacy: "confidential",
      recipient_gender: "male",
      medical_diagnosis: "Severe illness (records not publicly detailed)",
      cure_details: "Healed through prayer to Kateri.",
      cure_characteristics: "instant_complete",
      was_medically_verified: true,
      intercessory_medium: "prayer_only",
      vatican_recognized: true,
      used_for_beatification: true,
      used_for_canonization: false,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: false,
    },
    {
      saint_id: saintId("kateri-tekakwitha"),
      slug: "healing-of-jake-finkbonner",
      title: "Healing of Jake Finkbonner",
      miracle_category: "intercessory",
      type: "healing",
      topics: ["children", "infectious", "hope", "native-and-indigenous"],
      date_of_event: "2006-01-01",
      date_precision: "year",
      timing_relative_to_saint_death: "posthumous",
      location_name: "Ferndale, Washington",
      country: "USA",
      region: "Washington",
      recipient_name: "Jake Finkbonner",
      recipient_privacy: "public",
      recipient_gender: "male",
      recipient_age_at_event: 6,
      medical_diagnosis: "Necrotizing fasciitis (flesh-eating bacteria) from facial injury",
      cure_details:
        "Infection spreading rapidly, doctors said he would die or require extensive facial disfigurement. Relic of Kateri applied, prayers offered. Infection stopped, fully recovered without scarring.",
      cure_characteristics: "instant_complete",
      was_medically_verified: true,
      intercessory_medium: "relic",
      vatican_recognized: true,
      vatican_medical_board_verdict: "Declared medically inexplicable",
      used_for_beatification: false,
      used_for_canonization: true,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },
    {
      saint_id: saintId("kateri-tekakwitha"),
      slug: "vanishing-of-smallpox-scars",
      title: "Vanishing of Smallpox Scars at Death",
      miracle_category: "associated",
      type: "other",
      topics: ["dermatological", "native-and-indigenous", "perseverance"],
      date_of_event: "1680-04-17",
      date_precision: "exact_day",
      timing_relative_to_saint_death: "during_lifetime",
      location_name: "Kahnawake, Quebec",
      country: "Canada",
      region: "Quebec",
      recipient_name: "St. Kateri Tekakwitha",
      recipient_privacy: "public",
      recipient_gender: "female",
      recipient_age_at_event: 24,
      medical_diagnosis: "Smallpox scarring (survived epidemic at age 4, left with facial scarring and impaired vision)",
      cure_details:
        "Moments after her death, witnesses observed that the smallpox scars that had marked Kateri's face since childhood completely vanished. Her skin became smooth and beautiful. Witnessed by multiple people present at her deathbed and cited in her canonization process.",
      cure_characteristics: "not_applicable",
      was_medically_verified: false,
      intercessory_medium: "not_applicable",
      vatican_recognized: true,
      used_for_beatification: false,
      used_for_canonization: false,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },

    // ── André Bessette ────────────────────────────────────────────────────────
    {
      saint_id: saintId("andre-bessette"),
      slug: "healing-of-joseph-audet",
      title: "Healing of Joseph Audet",
      miracle_category: "intercessory",
      type: "healing",
      topics: ["infectious", "respiratory", "hope"],
      date_of_event: "1920-01-01",
      date_precision: "decade",
      timing_relative_to_saint_death: "during_lifetime",
      location_name: "Montreal, Quebec",
      country: "Canada",
      region: "Quebec",
      recipient_name: "Joseph Audet",
      recipient_privacy: "public",
      recipient_gender: "male",
      medical_diagnosis: "Severe tuberculosis (incurable, given up on by doctors)",
      cure_details:
        "Prayed at St. Joseph's Oratory, applied oil from lamp burning at St. Joseph's statue. Brother Andre blessed him and he recovered.",
      cure_characteristics: "instant_complete",
      was_medically_verified: true,
      intercessory_medium: "blessed_oil",
      vatican_recognized: true,
      used_for_beatification: true,
      used_for_canonization: false,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },
    {
      saint_id: saintId("andre-bessette"),
      slug: "healing-of-mario-de-montigny",
      title: "Healing of Mario De Montigny",
      miracle_category: "intercessory",
      type: "healing",
      topics: ["orthopedic", "children", "hope"],
      date_of_event: "1991-03-13",
      date_precision: "exact_day",
      timing_relative_to_saint_death: "posthumous",
      location_name: "Montreal, Quebec",
      country: "Canada",
      region: "Quebec",
      recipient_name: "Mario De Montigny",
      recipient_privacy: "public",
      recipient_gender: "male",
      recipient_age_at_event: 10,
      medical_diagnosis: "Severe tarsal fracture to foot that would not heal (after ATV accident)",
      cure_details:
        "Doctors said permanent limp or amputation required. Family prayed to Brother Andre and applied blessed oil. Foot healed completely and normally.",
      cure_characteristics: "instant_complete",
      was_medically_verified: true,
      intercessory_medium: "blessed_oil",
      vatican_recognized: true,
      vatican_medical_board_verdict: "Declared medically inexplicable",
      used_for_beatification: false,
      used_for_canonization: true,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },

    // ── Maximilian Kolbe ──────────────────────────────────────────────────────
    {
      saint_id: saintId("maximilian-kolbe"),
      slug: "healing-of-maria-gasior",
      title: "Healing of Maria Gasior",
      miracle_category: "intercessory",
      type: "healing",
      topics: ["gastrointestinal", "infectious", "hope"],
      date_of_event: "1940-01-01",
      date_precision: "decade",
      timing_relative_to_saint_death: "posthumous",
      country: "Poland",
      recipient_name: "Maria Gasior",
      recipient_privacy: "public",
      recipient_gender: "female",
      medical_diagnosis: "Intestinal tuberculosis (advanced, considered terminal)",
      cure_details: "Prayed to Maximilian Kolbe for intercession. Complete recovery.",
      cure_characteristics: "instant_complete",
      was_medically_verified: true,
      intercessory_medium: "prayer_only",
      vatican_recognized: true,
      used_for_beatification: true,
      used_for_canonization: false,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: false,
    },
    {
      saint_id: saintId("maximilian-kolbe"),
      slug: "healing-of-angela-testoni",
      title: "Healing of Angela Testoni",
      miracle_category: "intercessory",
      type: "healing",
      topics: ["gastrointestinal", "perseverance", "hope"],
      date_of_event: "1950-01-01",
      date_precision: "decade",
      timing_relative_to_saint_death: "posthumous",
      country: "Italy",
      recipient_name: "Angela Testoni",
      recipient_privacy: "public",
      recipient_gender: "female",
      medical_diagnosis: "Calcified peritoneum / severe intestinal disease (extensive calcificatio peritonealis)",
      cure_details: "Healing attributed to Kolbe's intercession. Declared medically inexplicable.",
      cure_characteristics: "instant_complete",
      was_medically_verified: true,
      intercessory_medium: "prayer_only",
      vatican_recognized: true,
      vatican_medical_board_verdict: "Declared medically inexplicable",
      used_for_beatification: false,
      used_for_canonization: true,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },

    // ── Louis & Zélie Martin ──────────────────────────────────────────────────
    {
      saint_id: saintId("louis-martin"),
      slug: "healing-of-carmen",
      title: "Healing of Carmen (Respiratory)",
      miracle_category: "intercessory",
      type: "healing",
      topics: ["respiratory", "children", "hope", "saints-of-everyday-life"],
      date_of_event: "1980-01-01",
      date_precision: "decade",
      timing_relative_to_saint_death: "posthumous",
      country: "Spain",
      recipient_name: "Carmen",
      recipient_privacy: "first_name_only",
      recipient_gender: "female",
      medical_diagnosis: "Severe lung condition (terminal respiratory disease)",
      cure_details: "Healing prayed for through the intercession of Louis and Zelie Martin.",
      cure_characteristics: "instant_complete",
      was_medically_verified: true,
      intercessory_medium: "prayer_only",
      vatican_recognized: true,
      vatican_medical_board_verdict: "Declared medically inexplicable",
      used_for_beatification: true,
      used_for_canonization: false,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },
    {
      saint_id: saintId("zelie-martin"),
      slug: "healing-of-pietro",
      title: "Healing of Pietro (Respiratory Failure)",
      miracle_category: "intercessory",
      type: "healing",
      topics: ["respiratory", "children", "hope", "saints-of-everyday-life", "marriage"],
      date_of_event: "2012-01-01",
      date_precision: "year",
      timing_relative_to_saint_death: "posthumous",
      country: "Italy",
      recipient_name: "Pietro",
      recipient_privacy: "first_name_only",
      recipient_gender: "male",
      recipient_age_at_event: 0,
      medical_diagnosis: "Severe respiratory failure (near death, doctors gave no hope)",
      cure_details:
        "Infant's parents prayed to the Martins. Baby recovered fully and doctors could not explain it.",
      cure_characteristics: "instant_complete",
      was_medically_verified: true,
      intercessory_medium: "prayer_only",
      vatican_recognized: true,
      vatican_medical_board_verdict: "Declared medically inexplicable",
      used_for_beatification: false,
      used_for_canonization: true,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },

    // ── Carlo Acutis ──────────────────────────────────────────────────────────
    {
      saint_id: saintId("carlo-acutis"),
      slug: "healing-of-matheus",
      title: "Healing of Matheus (Pancreatic Disease)",
      miracle_category: "intercessory",
      type: "healing",
      topics: ["children", "gastrointestinal", "hope", "perseverance"],
      date_of_event: "2010-01-01",
      date_precision: "decade",
      timing_relative_to_saint_death: "posthumous",
      location_name: "Campo Grande, Brazil",
      country: "Brazil",
      recipient_name: "Matheus Vianna",
      recipient_privacy: "first_name_only",
      recipient_gender: "male",
      medical_diagnosis: "Rare pancreatic disease (possibly annular pancreas)",
      cure_details:
        "Mother prayed to Carlo after learning about his story. Doctors said surgery was only option. Boy recovered spontaneously.",
      cure_characteristics: "instant_complete",
      was_medically_verified: true,
      intercessory_medium: "prayer_only",
      vatican_recognized: true,
      vatican_medical_board_verdict: "Declared medically inexplicable",
      used_for_beatification: true,
      used_for_canonization: false,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },
    {
      saint_id: saintId("carlo-acutis"),
      slug: "healing-of-valeria-valverde",
      title: "Healing of Valeria Valverde",
      miracle_category: "intercessory",
      type: "healing",
      topics: ["neurological", "youth", "mothers", "hope"],
      date_of_event: "2022-01-01",
      date_precision: "year",
      timing_relative_to_saint_death: "posthumous",
      location_name: "Florence, Italy",
      country: "Italy",
      region: "Tuscany",
      recipient_name: "Valeria Valverde",
      recipient_privacy: "public",
      recipient_gender: "female",
      medical_diagnosis: "Brain haemorrhage from falling off a bicycle; doctors gave low chance of survival",
      cure_details:
        "Mother Lilliana prayed for Carlo's intercession and visited his tomb in Assisi. Same day, Valeria began breathing independently. Next day, she was able to walk with all evidence of the haemorrhage having disappeared.",
      cure_characteristics: "instant_complete",
      was_medically_verified: true,
      intercessory_medium: "tomb_prayer",
      vatican_recognized: true,
      vatican_decree_date: "2024-05-23",
      vatican_medical_board_verdict:
        "Recognized as second miracle by Pope Francis on May 23, 2024; canonized Sept 7, 2025",
      used_for_beatification: false,
      used_for_canonization: true,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },
    {
      saint_id: saintId("carlo-acutis"),
      slug: "body-of-carlo-acutis-wax-encased",
      title: "Body of Carlo Acutis (Wax-Encased Display)",
      miracle_category: "associated",
      type: "other",
      topics: ["saints-bodies", "youth", "eucharistic"],
      date_of_event: "2020-01-01",
      date_precision: "year",
      timing_relative_to_saint_death: "posthumous",
      location_name: "Sanctuary of Santa Maria Maggiore, Assisi",
      country: "Italy",
      region: "Umbria",
      recipient_privacy: "not_applicable",
      recipient_gender: "not_applicable",
      cure_details:
        "Carlo's body was exhumed in 2007 and found to have undergone normal decay (not incorrupt). His remains are displayed in a glass tomb at the Sanctuary of Santa Maria Maggiore in Assisi, covered with a wax layer molded to resemble his living appearance — a common Italian tradition also used for St. John XXIII. The Church has NOT declared his body incorrupt. He wears a tracksuit and sneakers. Popular online claims of incorruptibility are inaccurate.",
      cure_characteristics: "not_applicable",
      was_medically_verified: true,
      medical_verification_date: "2007-01-01",
      intercessory_medium: "not_applicable",
      vatican_recognized: false,
      used_for_beatification: false,
      used_for_canonization: false,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },

    // ── Juan Diego ────────────────────────────────────────────────────────────
    {
      saint_id: saintId("juan-diego"),
      slug: "healing-of-juan-jose-barragan-silva",
      title: "Healing of Juan José Barragán Silva",
      miracle_category: "intercessory",
      type: "healing",
      topics: ["neurological", "elderly", "native-and-indigenous", "hope"],
      date_of_event: "1990-05-03",
      date_precision: "exact_day",
      timing_relative_to_saint_death: "posthumous",
      location_name: "Queretaro, Mexico",
      country: "Mexico",
      recipient_name: "Juan José Barragán Silva",
      recipient_privacy: "public",
      recipient_gender: "male",
      recipient_age_at_event: 20,
      medical_diagnosis:
        "Severe trauma from 10m head-first fall: spinal/neck/cranial fractures, intracranial hemorrhage",
      cure_details:
        "Mother invoked Juan Diego. He went into a coma and emerged on May 6 (Juan Diego's beatification day), discharged fully recovered a week later.",
      cure_characteristics: "instant_complete",
      was_medically_verified: true,
      medical_verification_date: "1998-01-01",
      intercessory_medium: "prayer_only",
      vatican_recognized: true,
      vatican_decree_date: "2001-12-20",
      vatican_medical_board_verdict:
        "5 consultors unanimous medically inexplicable (1998); theological board unanimous (May 2001); papal approval Dec 20, 2001",
      used_for_beatification: false,
      used_for_canonization: true,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },
    {
      saint_id: saintId("juan-diego"),
      slug: "tilma-of-guadalupe",
      title: "The Tilma of Our Lady of Guadalupe",
      miracle_category: "associated",
      type: "miraculous_image",
      topics: ["marian", "miraculous-images", "native-and-indigenous", "conversion"],
      date_of_event: "1531-12-09",
      date_precision: "exact_day",
      timing_relative_to_saint_death: "during_lifetime",
      location_name: "Tepeyac Hill, Mexico City",
      country: "Mexico",
      region: "Mexico City",
      recipient_privacy: "not_applicable",
      recipient_gender: "not_applicable",
      cure_details:
        "Our Lady appeared to Juan Diego. Bishop demanded a sign. Juan Diego gathered Castilian roses (out of season) in his tilma. When opened before the bishop, the image of Our Lady was miraculously imprinted on the fabric.",
      cure_characteristics: "not_applicable",
      was_medically_verified: false,
      intercessory_medium: "not_applicable",
      vatican_recognized: true,
      used_for_beatification: false,
      used_for_canonization: false,
      synopsis: LOREM_SYNOPSIS,
      has_primary_sources: true,
    },
  ]);

  console.log("Seeding complete.");
  console.log(`  Saints: ${insertedSaints.length}`);
  console.log("  Saint relations: 2");
  console.log("  Miracles: 26");
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
